<?php
declare(strict_types=1);

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use PerspectiveTeam\JustCheckMeOut\ViewModel\HeadlessComponentRenderer;

/** @var Template $block */
/** @var Escaper $escaper */

/** @var HeadlessComponentRenderer $components */
$components = $block->getData('headlessComponentRenderer');
?>

<template x-for="item in <?= $block->getData('alpine/expr/items') ?>"
          :key="<?= $block->getData('alpine/expr/value') ?>">
    <p>
        <input type="radio"
               name="<?= $block->getData('key') ?>"
               :value="<?= $block->getData('alpine/expr/value') ?>"
               :checked="<?= $block->getData('alpine/expr/current') ?> === $el.value"
               @click="<?= $block->getData('alpine/fn/select') ?>(item)"/>
        <span x-text="<?= $block->getData('alpine/expr/label') ?>"></span>
    </p>
</template>
