<?php
declare(strict_types=1);

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use PerspectiveTeam\JustCheckMeOut\ViewModel\HeadlessComponentRenderer;
use PerspectiveTeam\JustCheckMeOut\ViewModel\QuoteViewModel;
use PerspectiveTeam\JustCheckMeOut\ViewModel\SsrGraphqlViewModel;

/** @var Template $block */
/** @var Escaper $escaper */

/** @var SsrGraphqlViewModel $gql */
$gql = $block->getData('ssrGqlViewModel');

/** @var QuoteViewModel $quoteViewModel */
$quoteViewModel = $block->getData('quoteViewModel');

/** @var HeadlessComponentRenderer $components */
$components = $block->getData('headlessComponentRenderer');

$scriptTagId = uniqid('psteam-justcheckmeout-api-script_');
?>

<script id="<?= $scriptTagId ?>">
    window.psteamJustCheckMeOutApiV1 = {
        globals: { // todo: via alpinejs::$store
            _: {
                placeOrderHooks: {},
            },
            registerJsPlaceOrderHook: function (paymentMethodCode, handler) {
                window.psteamJustCheckMeOutApiV1.globals._.placeOrderHooks[paymentMethodCode] = handler;
            },
            getJsPlaceOrderHook: function (paymentMethodCode) {
                return window.psteamJustCheckMeOutApiV1.globals._.placeOrderHooks[paymentMethodCode];
            }
        },
        bus: {
            _el: document.getElementById("<?= $scriptTagId ?>"),
            on: function (event, callback) {
                const nativeCallback = async (e) => {
                    await callback(e.detail.payload);
                };

                window.psteamJustCheckMeOutApiV1
                    .bus
                    ._el
                    .addEventListener(`psteam_justcheckmeout::${event}`, nativeCallback);
                return () => window.psteamJustCheckMeOutApiV1
                    .bus
                    ._el
                    .removeEventListener(`psteam_justcheckmeout::${event}`, nativeCallback);
            },
            fire: function (event, payload) {
                window.psteamJustCheckMeOutApiV1
                    .bus
                    ._el
                    .dispatchEvent(new CustomEvent(`psteam_justcheckmeout::${event}`, {
                        detail: {
                            payload,
                        }
                    }));
            },
            then: function (promise, event, callback = undefined, once = true) {
                promise.then(async (result) => {
                    if (!!callback) {
                        if (once) {
                            callback(result)
                        } else {
                            window.psteamJustCheckMeOutApiV1.bus.on(event, callback);
                        }
                    }
                    window.psteamJustCheckMeOutApiV1.bus.fire(event, result);
                });
            }
        },
        fn: {},
        component: {},
    };
</script>

<?php
    $innerBlockData = [
        'ssrGqlViewModel' => $gql,
        'quoteViewModel' => $quoteViewModel,
    ];

    $innerBlocks = [
        'fn/graphql',
        'component/customer-email-form',
        'component/shipping-address-form',
        'component/unified-address-form',
        'component/shipping-method-list',
        'component/payment-method-list',
        'component/place-order-button',
    ];

    foreach ($innerBlocks as $name) {
        echo $components->render("PerspectiveTeam_JustCheckMeOut::api/$name.phtml", $innerBlockData);
    }
?>

<?= $block->getChildHtml('checkout.onepage.api.after') ?>
