<?php
declare(strict_types=1);

use Magento\Framework\Escaper;
use NeutromeLabs\JustCheckMeOut\Block\Stateful;

/** @var Stateful $block */
/** @var Escaper $escaper */

$cartId = $block->quoteViewModel->getMaskedQuoteId();
$scriptTagId = uniqid('justcheckmeout-api-script_');
?>

<script id="<?= $scriptTagId ?>">
    window.justCheckMeOutApiV1 = {
        globals: {
            /**
             * @return {string}
             */
            cartId: function () {
                return Alpine.store('justcheckmeout::cartId') ?? <?= "'$cartId'" ?>;
            },
            registerPlaceOrderGuard: function (slug, priority, handler) {
                const guards = Alpine.store('justcheckmeout::placeOrderGuards') ?? {};
                guards[slug] = {priority, handler};
                Alpine.store('justcheckmeout::placeOrderGuards', guards);
            },
            getPlaceOrderGuardHandlers: function () {
                const guards = Alpine.store('justcheckmeout::placeOrderGuards') ?? {};
                return Object.entries(guards)
                    .sort((a, b) => a[1].priority - b[1].priority)
                    .map(([slug, data]) => data.handler);
            },
            registerPlaceOrderHook: function (paymentMethodCode, handler) {
                const hooks = Alpine.store('justcheckmeout::placeOrderHooks') ?? {};
                hooks[paymentMethodCode] = handler;
                Alpine.store('justcheckmeout::placeOrderHooks', hooks);
            },
            getPlaceOrderHook: function (paymentMethodCode) {
                return (Alpine.store('justcheckmeout::placeOrderHooks') ?? {})[paymentMethodCode];
            },
        },
        bus: {
            /**
             * @param {string} event
             * @param {(payload: any, abort: ?AbortController) => void|Promise<void>} callback
             *
             * @returns {void}
             */
            on: function (event, callback) {
                const events = Alpine.store(`justcheckmeout::events::${event}`) ?? [];
                events.push(callback);
                Alpine.store(`justcheckmeout::events::${event}`, events);
            },
            /**
             * @param {string} event
             * @param {any} payload
             * @param {AbortController} abort
             *
             * @returns {Promise<void>}
             */
            fire: async function (event, payload = undefined, abort = undefined) {
                const events = Alpine.store(`justcheckmeout::events::${event}`) ?? [];
                for (const callback of events) {
                    abort?.signal.throwIfAborted();
                    await callback(payload, abort);
                }
            },
        },
        fn: {},
        component: {},
    };
</script>

<?= $block->getChildHtml('justcheckmeout.api.after') ?>
