<?php
declare(strict_types=1);

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use NeutromeLabs\JustCheckMeOut\Block\Stateful;

/** @var Stateful $block */
/** @var Escaper $escaper */
?>

<div class="justcheckmeout__container">
    <div class="justcheckmeout__main">
        <?= $block->getChildHtml('unified-address-form') ?>
        <?= $block->getChildHtml('shipping-method-list') ?>
    </div>
    <div class="justcheckmeout__sidebar">
        <?= $block->getChildHtml('items') ?>
        <div class="justcheckmeout__sidebar-checkout">
            <?= $block->getChildHtml('totals') ?>
            <?= $block->getChildHtml('payment-method-list') ?>
        </div>
        <?= $block->getChildHtml('place-order-button') ?>
    </div>
</div>
