<?php
declare(strict_types=1);

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use PerspectiveTeam\JustCheckMeOut\ViewModel\HeadlessComponentRenderer;
use PerspectiveTeam\JustCheckMeOut\ViewModel\QuoteViewModel;

/** @var Template $block */
/** @var Escaper $escaper */

/** @var QuoteViewModel $quoteViewModel */
$quoteViewModel = $block->getData('quoteViewModel');
/** @var HeadlessComponentRenderer $components */
$components = $block->getData('headlessComponentRenderer');

$quote = $quoteViewModel->getQuote();
?>

<div class="flex flex-col h-full space-y-6">
    <div class="relative grid gap-3 sm:gap-8">
        <?php foreach ($quote->getAllVisibleItems() as $item): ?>
        <div class="flex gap-4 mt-2">
            <div class="flex-none relative">
                <img src="https://app.demo-just-check-me-out.test/media/catalog/product/<?= $item->getProduct()->getImage() ?>"
                     width="64"
                     height="64"
                     alt="<?= $item->getName() ?>"
                     loading="lazy"
                     class="rounded">

                <span class="h-5 w-5 py-1
                             text-xs text-center text-white
                             leading-none
                             rounded-full
                             bg-gray-dark
                             block absolute
                             -right-1 top-0 transform -translate-y-1/2">
                                    <?= $item->getQty() ?>
                </span>
            </div>

            <div class="flex-grow space-y-2">
                <div class="flex gap-4 md:gap-0 justify-between flex-col md:flex-row">
                    <div class="product-title">
                        <p class="font-bold"><?= $item->getName() ?></p>
                        <p class="text-sm"><?= $item->getSku() ?></p>
                    </div>
                    <div class="product-price">
                        <span><?= number_format(floatval($item->getPrice()), 2) ?> <?= $quote->getQuoteCurrencyCode() ?></span>
                    </div>
                </div>

            </div>
        </div>
        <?php endforeach; ?>
    </div>
</div>
