<?php
declare(strict_types=1);

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use PerspectiveTeam\JustCheckMeOut\ViewModel\HeadlessComponentRenderer;
use PerspectiveTeam\JustCheckMeOut\ViewModel\QuoteViewModel;

/** @var Template $block */
/** @var Escaper $escaper */

/** @var QuoteViewModel $quoteViewModel */
$quoteViewModel = $block->getData('quoteViewModel');
/** @var HeadlessComponentRenderer $components */
$components = $block->getData('headlessComponentRenderer');

$radioListKey = uniqid('payment_method_');
?>

<form action="#" x-data="window.justCheckMeOutApiV1.component.createPaymentMethodList()">
    <?= $components->render('block/messages', [
        'scope' => 'payment-method-list',
    ], 'justcheckmeout.onepage.payment-method-list.messages') ?>

    <?= $components->render('block/radio-list-with-details', [
        'key' => $radioListKey,
        'empty' => 'No payment methods available',
        'alpine' => [
            'expr' => [
                'disabled' => '!interactive',
                'items' => 'methodsAvailable',
                'value' => 'item.code',
                'current' => 'selectedMethod',
                'label' => 'item.title',
                'details' => 'selectedMethodDetailsHtml',
                'select' => 'await selectMethod(item)',
            ],
        ]
    ], 'justcheckmeout.onepage.payment-method-list.list') ?>
</form>
