<?php
declare(strict_types=1);

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use PerspectiveTeam\JustCheckMeOut\ViewModel\HeadlessComponentRenderer;
use PerspectiveTeam\JustCheckMeOut\ViewModel\QuoteViewModel;

/** @var Template $block */
/** @var Escaper $escaper */

/** @var QuoteViewModel $quoteViewModel */
$quoteViewModel = $block->getData('quoteViewModel');
/** @var HeadlessComponentRenderer $components */
$components = $block->getData('headlessComponentRenderer');
?>

<div x-data="window.justCheckMeOutApiV1.component.createPlaceOrder()">
    <?= $components->render('atom/button', [
        'text' => 'Place Order',
        'attributes' => [
            'type' => 'button',
            ':disabled' => '!interactive',
            '@click' => 'await placeAndGoNext()',
        ]
    ]) ?>
</div>
