<?php
declare(strict_types=1);

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use PerspectiveTeam\JustCheckMeOut\ViewModel\HeadlessComponentRenderer;
use PerspectiveTeam\JustCheckMeOut\ViewModel\QuoteViewModel;

/** @var Template $block */
/** @var Escaper $escaper */

/** @var QuoteViewModel $quoteViewModel */
$quoteViewModel = $block->getData('quoteViewModel');
/** @var HeadlessComponentRenderer $components */
$components = $block->getData('headlessComponentRenderer');

$radioListKey = uniqid('shipping_method_');
?>

<form action="#" x-data="window.justCheckMeOutApiV1.component.createShippingMethodList()">
    <?= $components->render('block/messages', [
        'scope' => 'shipping-method-list',
    ], 'justcheckmeout.onepage.shipping-method-list.messages') ?>

    <?= $components->render('block/radio-list-with-details', [
        'key' => $radioListKey,
        'alpine' => [
            'expr' => [
                'disabled' => '!interactive',
                'items' => 'methodsAvailable',
                'value' => '`${item.carrier_code}_${item.method_code}`',
                'current' => 'selectedMethod',
                'label' => '`${item.carrier_title} ${item.method_title} - ${item.price_incl_tax.value} ${item.price_incl_tax.currency}`',
                'details' => 'selectedMethodDetailsHtml',
                'select' => 'await selectMethod(item)',
            ],
        ]
    ], 'justcheckmeout.onepage.shipping-method-list.list') ?>
</form>
