<?php
declare(strict_types=1);

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use PerspectiveTeam\JustCheckMeOut\ViewModel\HeadlessComponentRenderer;
use PerspectiveTeam\JustCheckMeOut\ViewModel\QuoteViewModel;

/** @var Template $block */
/** @var Escaper $escaper */

/** @var QuoteViewModel $quoteViewModel */
$quoteViewModel = $block->getData('quoteViewModel');
/** @var HeadlessComponentRenderer $components */
$components = $block->getData('headlessComponentRenderer');

$quote = $quoteViewModel->getQuote();
?>

<div x-data="window.justCheckMeOutApiV1.component.createTotals()">
    <template x-if="subtotal()">
        <div class="flex justify-between gap-4 md:gap-0">
            <span>Subtotal</span>
            <span x-text="subtotal().value + ' ' + subtotal().currency"></span>
        </div>
    </template>
    <template x-for="tax in taxes()">
        <div class="flex justify-between gap-4 md:gap-0">
            <span x-text="tax.label"></span>
            <span x-text="tax.amount.value + ' ' + tax.amount.currency"></span>
        </div>
    </template>
    <template x-if="grandTotal()">
        <div class="flex justify-between gap-4 md:gap-0">
            <span>Grand Total</span>
            <span x-text="grandTotal().value + ' ' + grandTotal().currency"></span>
        </div>
    </template>
</div>
