<?php
declare(strict_types=1);

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use PerspectiveTeam\JustCheckMeOut\ViewModel\HeadlessComponentRenderer;
use PerspectiveTeam\JustCheckMeOut\ViewModel\QuoteViewModel;

/** @var Template $block */
/** @var Escaper $escaper */

/** @var QuoteViewModel $quoteViewModel */
$quoteViewModel = $block->getData('quoteViewModel');
/** @var HeadlessComponentRenderer $components */
$components = $block->getData('headlessComponentRenderer');

$quote = $quoteViewModel->getQuote();
$address = $quote->getShippingAddress();

$formId = uniqid('unified-address-form_');
$addressesRadioListKey = uniqid('customer-shipping-address-')
?>

<form id="<?= $formId ?>" x-data="window.justCheckMeOutApiV1.component.createUnifiedAddressForm(
    document.querySelector(<?= "`#$formId > div[x-ref=email]`" ?>)
)" @submit.prevent="await save()">
    <ul>
        <template x-for="address in addressesFromAddressBook()" :key="address.id">
            <li>
                <span>
                    <input type="radio"
                           name="<?= $addressesRadioListKey ?>"
                           :value="address.id"
                           :checked="selectedAddressId === address.id"
                           @click="await selectAddressFromBook(address)"
                    />
                    <span x-text="`#${address.id}`"></span>
                </span>
                <p>
                    <span x-text="address.firstname"></span>
                    <span x-text="address.lastname"></span>
                </p>
                <p>
                    <span x-text="address.telephone"></span>
                </p>
                <p>
                    <span x-text="address.city"></span>
                    <span x-text="address.street"></span>
                </p>
            </li>
        </template>
        <template x-if="addressesFromAddressBook().length">
            <li>
                <hr>
                <p>
                    <input type="radio"
                           name="<?= $addressesRadioListKey ?>"
                           value="0"
                           :checked="!selectedAddressId"
                           @click="await selectAddressFromBook(null)"
                    />
                    <span>Use new address</span>
                </p>
            </li>
        </template>
    </ul>

    <div class="mb-4" x-data="window.justCheckMeOutApiV1.component.createCustomerEmailForm()" x-ref="email">
        <?= $components->render('block/input-text', [
            'label' => 'Email',
            'attributes' => [
                'type' => 'email',
                'name' => 'email',
                'required' => 1,
                'value' => $address->getEmail(),
                'x-model' => 'displayEmail',
                ':disabled' => '!interactive',
                '@focusout' => 'await save()',
            ]
        ], 'justcheckmeout.onepage.customer-email-form.input-email') ?>
    </div>

    <?= $components->render('block/address-fieldset', [
        'fields' => [
            'firstname' => [
                'required' => 1,
                'label' => 'First Name',
                'value' => $address->getFirstname(),
                ':disabled' => '!unifiedInteractive',
                'x-model' => 'formData.firstname',
            ],
            'lastname' => [
                'required' => 1,
                'label' => 'Last Name',
                'value' => $address->getLastname(),
                ':disabled' => '!unifiedInteractive',
                'x-model' => 'formData.lastname',
            ],
            'telephone' => [
                'label' => 'Telephone',
                'value' => $address->getTelephone(),
                ':disabled' => '!unifiedInteractive',
                'x-model' => 'formData.telephone',
            ],
            'country' => [
                'required' => 1,
                'label' => 'Country',
                'value' => $address->getCountryId(),
                ':disabled' => '!unifiedInteractive',
                'x-model' => 'formData.country_code',
            ],
            'city' => [
                'required' => 1,
                'label' => 'City',
                'value' => $address->getCity(),
                ':disabled' => '!unifiedInteractive',
                'x-model' => 'formData.city',
            ],
            'postcode' => [
                'required' => 1,
                'label' => 'Postcode',
                'value' => $address->getPostcode(),
                ':disabled' => '!unifiedInteractive',
                'x-model' => 'formData.postcode',
            ],
            'street_1' => [
                'required' => 1,
                'label' => 'Street',
                'value' => $address->getStreetLine(1),
                ':disabled' => '!unifiedInteractive',
                'x-model' => 'formData.street[0]',
            ],
        ]
    ]) ?>

    <?= $components->render('atom/button', [
        'text' => 'Save',
        'attributes' => [
            'type' => 'submit',
            ':disabled' => '!unifiedInteractive',
        ]
    ]) ?>
</form>
