<?php
declare(strict_types=1);

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use PerspectiveTeam\JustCheckMeOut\ViewModel\HeadlessComponentRenderer;
use PerspectiveTeam\JustCheckMeOut\ViewModel\QuoteViewModel;

/** @var Template $block */
/** @var Escaper $escaper */

/** @var QuoteViewModel $quoteViewModel */
$quoteViewModel = $block->getData('quoteViewModel');
/** @var HeadlessComponentRenderer $components */
$components = $block->getData('headlessComponentRenderer');

$quote = $quoteViewModel->getQuote();
$address = $quote->getShippingAddress();

$formId = uniqid('unified-address-form_');
$addressesRadioListKey = uniqid('customer-shipping-address-')
?>

<form id="<?= $formId ?>" x-data="window.justCheckMeOutApiV1.component.createUnifiedAddressForm(
    document.querySelector(<?= "`#$formId > div[x-ref=email]`" ?>)
)" @submit.prevent="await save()">
    <div>
        <?= $components->render('block/messages', [
            'scope' => 'shipping-address',
        ], 'justcheckmeout.onepage.shipping-address-form.messages') ?>
    </div>
    <ul>
        <template x-for="address in addressesFromAddressBook()" :key="address.id">
            <li>
                <span>
                    <input type="radio"
                           name="<?= $addressesRadioListKey ?>"
                           :value="address.id"
                           :checked="selectedAddressId === address.id"
                           @click="await selectAddressFromBook(address)"
                    />
                    <span x-text="`#${address.id}`"></span>
                </span>
                <p>
                    <span x-text="address.firstname"></span>
                    <span x-text="address.lastname"></span>
                </p>
                <p>
                    <span x-text="address.telephone"></span>
                </p>
                <p>
                    <span x-text="address.city"></span>
                    <span x-text="address.street"></span>
                </p>
            </li>
        </template>
        <template x-if="addressesFromAddressBook().length">
            <li>
                <hr>
                <p>
                    <input type="radio"
                           name="<?= $addressesRadioListKey ?>"
                           value="0"
                           :checked="!selectedAddressId"
                           @click="await selectAddressFromBook(null)"
                    />
                    <span>Use new address</span>
                </p>
            </li>
        </template>
    </ul>

    <div class="mb-4" x-data="window.justCheckMeOutApiV1.component.createCustomerEmailForm()" x-ref="email">
        <?= $components->render('block/input-text', [
            'label' => 'Email',
            'attributes' => [
                'type' => 'email',
                'name' => 'email',
                'required' => 1,
                'value' => $address->getEmail(),
                'x-model' => 'displayEmail',
                ':disabled' => '!interactive',
                '@focusout' => 'await save()',
            ]
        ], 'justcheckmeout.onepage.customer-email-form.input-email') ?>
    </div>

    <div class="flex flex-col gap-4 mb-4"
         x-data="{regions: undefined}"
    >
        <span></span> <!-- form spacing -->

        <div class="w-full flex gap-4">
            <div class="w-1/2">
                <?= $components->render('block/input-text', [
                    'label' => 'Firstname',
                    'attributes' => [
                        'name' => 'firstname',
                        'required' => 1,
                        'value' => $address->getFirstname(),
                        ':disabled' => '!unifiedInteractive',
                        'x-model' => 'formData.firstname',
                    ]
                ], 'justcheckmeout.onepage.shipping-address-form.input-firstname') ?>
            </div>

            <div class="w-1/2">
                <?= $components->render('block/input-text', [
                    'label' => 'Lastname',
                    'attributes' => [
                        'name' => 'lastname',
                        'required' => 1,
                        'value' => $address->getLastname(),
                        ':disabled' => '!unifiedInteractive',
                        'x-model' => 'formData.lastname',
                    ]
                ], 'justcheckmeout.onepage.shipping-address-form.input-lastname') ?>
            </div>
        </div>

        <div class="w-full">
            <?= $components->render('block/input-text', [
                'label' => 'Telephone',
                'attributes' => [
                    'name' => 'telephone',
                    'required' => 1,
                    'value' => $address->getTelephone(),
                    ':disabled' => '!unifiedInteractive',
                    'x-model' => 'formData.telephone',
                ]
            ], 'justcheckmeout.onepage.shipping-address-form.input-telephone') ?>
        </div>

        <span></span> <!-- form spacing -->

        <div class="w-full flex gap-4">
            <div class="w-1/2">
                <?= $components->render('block/input-select', [
                    'label' => 'Country',
                    'alpine' => [
                        'props' => <<<JS
{
    selectedId: formData.country_code,
    initImpl: async function () {
        await this.search('');
        const regions = this.options.find(o => o.id === this.selectedId)?.regions;
        if (regions?.length > 0) {
            this.regions = regions;
            this.formData.region = null;
        }
    },
    searchImpl: async text => {
        const r = await window.justCheckMeOutApiV1.fn.fetchGql(
            `query {
  countries {
    id
    full_name_locale
    available_regions {
      id
      code
      name
    }
  }
}`);
        return r?.data?.countries?.map(x => {
            return {
                id: x.id,
                label: x.full_name_locale,
                regions: x.available_regions?.map(r => {
                    return {
                        id: r.id,
                        label: r.name,
                        code: r.code,
                    };
                }),
            };
        }) ?? [];
    }
}
JS,
                    ],
                    'attributes' => [
                        'wrapper' => [
                            'x-model' => 'formData.country_code',
                        ],
                        'input' => [
                            'name' => 'country_code',
                            'required' => 1,
                            ':disabled' => '!unifiedInteractive',
                            '@change' => <<<JS
regions = options.find(o => o.id === \$el.value)?.regions;
formData.region_id = null;
formData.region = null;
formData.city = null;
formData.postcode = null;
formData.street = [];
JS,
                        ],
                    ]
                ], 'justcheckmeout.onepage.shipping-address-form.input-country_code') ?>

            </div>

            <div class="w-1/2" x-show="regions?.length > 0">
                <?= $components->render('block/input-select', [
                    'label' => 'Region',
                    'alpine' => [
                        'props' => <<<JS
{
    selectedId: formData.region_id,
    initImpl: function () {
        this.\$watch('regions', async x => {
            await this.search('');
        });
    },
    searchImpl: async function (text) {
        return this.regions ?? [];
    }
}
JS,
                    ],
                    'attributes' => [
                        'wrapper' => [
                            'x-model' => 'formData.region_id',
                        ],
                        'input' => [
                            'name' => 'region_id',
                            ':required' => 'regions?.length > 0',
                            ':disabled' => '!unifiedInteractive',
                            '@change' => 'formData.region = null',
                        ],
                    ]
                ], 'justcheckmeout.onepage.shipping-address-form.input-region_id') ?>
            </div>

            <div class="w-1/2" x-show="!regions || regions.length === 0">
                <?= $components->render('block/input-text', [
                    'label' => 'Region',
                    'attributes' => [
                        'name' => 'region',
                        ':required' => '!regions || regions.length === 0',
                        'value' => $address->getRegion(),
                        ':disabled' => '!unifiedInteractive',
                        'x-model' => 'formData.region',
                    ]
                ], 'justcheckmeout.onepage.shipping-address-form.input-region') ?>
            </div>
        </div>

        <div class="w-full flex gap-4">
            <div class="w-1/2">
                <?= $components->render('block/input-text', [
                    'label' => 'City',
                    'attributes' => [
                        'name' => 'city',
                        'required' => 1,
                        'value' => $address->getCity(),
                        ':disabled' => '!unifiedInteractive',
                        'x-model' => 'formData.city',
                    ]
                ], 'justcheckmeout.onepage.shipping-address-form.input-city') ?>
            </div>

            <div class="w-1/2">
                <?= $components->render('block/input-text', [
                    'label' => 'Postcode',
                    'attributes' => [
                        'name' => 'postcode',
                        'required' => 1,
                        'value' => $address->getPostcode(),
                        ':disabled' => '!unifiedInteractive',
                        'x-model' => 'formData.postcode',
                    ]
                ], 'justcheckmeout.onepage.shipping-address-form.input-postcode') ?>
            </div>
        </div>

        <div class="w-full">
            <?= $components->render('block/input-text', [
                'label' => 'Street',
                'attributes' => [
                    'name' => 'street_1',
                    'required' => 1,
                    'value' => $address->getStreetLine(1),
                    ':disabled' => '!unifiedInteractive',
                    'x-model' => 'formData.street[0]',
                ]
            ], 'justcheckmeout.onepage.shipping-address-form.input-street_1') ?>
        </div>
    </div>

    <?= $components->render('atom/button', [
        'text' => 'Save',
        'attributes' => [
            'type' => 'submit',
            ':disabled' => '!unifiedInteractive',
        ]
    ]) ?>
</form>
