<?php
declare(strict_types=1);

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use PerspectiveTeam\SsrGraphql\ViewModel\SsrGraphqlViewModel;

/** @var Template $block */
/** @var Escaper $escaper */

/** @var SsrGraphqlViewModel $gql */
$gql = $block->getData('ssrGqlViewModel');
?>

<script>
    window.fetchMagento2Gql = async function (query, variables = {}, method = 'POST') {
        // todo: add support for GET requests
        const r = await fetch('<?= $gql->getBaseUrl() ?>graphql', {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
            },
            body: JSON.stringify({
                query,
                variables,
            }),
        });
        return await r.json();
    }

    window.createMagento2SsrGqlStub = function (query, variables, response = undefined) {
        <?php if ($gql->isDebug()): ?>
        console.log('ssr graphql stub: ', {
            query,
            variables,
            meta: response.__debug,
        });

        if (response?.errors?.length > 0) {
            console.error('error resolving ssr graphql response: ', {
                query,
                variables,
                errors: response.errors.length === 1 ? response.errors[0] : response.errors,
            });
        }
        <?php endif; ?>

        return {
            ssr: {
                query,
                variables,
                response,
            },
            fresh: false,
            data: response?.data,
            errors: response?.errors,
            fetch: async function (variables) {
                const r = await window.fetchMagento2Gql(this.ssr.query, {
                    ...this.ssr.variables,
                    ...variables,
                });

                <?php if ($gql->isDebug()): ?>
                if (r.errors?.length > 0) {
                    console.error('error fetching graphql response: ', {
                        query: this.ssr.query,
                        variables: this.ssr.variables,
                        errors: r.errors.length === 1 ? r.errors[0] : r.errors,
                    });
                }
                <?php endif; ?>

                return r;
            },
            refresh: async function (variables) {
                const r = await this.fetch(variables);
                this.fresh = true;
                this.data = r?.data;
                this.errors = r?.errors;
            }
        };
    }
</script>
