<?php
declare(strict_types=1);

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use PerspectiveTeam\SsrGraphql\ViewModel\SsrGraphqlViewModel;

/** @var Template $block */
/** @var Escaper $escaper */

/** @var SsrGraphqlViewModel $gql */
$gql = $block->getData('ssrGqlViewModel');
?>

<script>
    window.fetchMagento2Gql = async function (query, variables = {}) {
        const r = await fetch('<?= $gql->getBaseUrl() ?>/graphql', {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
            },
            body: JSON.stringify({
                query,
                variables,
            }),
        });
        return await r.json();
    }

    window.createMagento2SsrGqlStub = function (query, variables, response = undefined) {
        // todo: if debug
        if (response?.errors?.length > 0) {
            console.error('error resolving ssr graphql response: ', {
                query,
                variables,
                errors: response.errors.length === 1 ? response.errors[0] : response.errors,
            });
        }

        return {
            ssr: {
                variables,
                response,
            },
            fresh: false,
            data: response?.data,
            errors: response?.errors,
            fetch: async function (variables) {
                const r = await window.fetchMagento2Gql(query, {
                    ...this.ssr.variables,
                    ...variables,
                });

                // todo: if debug
                if (r.errors?.length > 0) {
                    console.error('error fetching graphql response: ', {
                        query,
                        variables,
                        errors: r.errors.length === 1 ? r.errors[0] : r.errors,
                    });
                }

                return r;
            },
            refresh: async function () {
                const r = await this.fetch();
                this.fresh = true;
                this.data = r?.data;
                this.errors = r?.errors;
            }
        };
    }
</script>
