<?php
declare(strict_types=1);

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use PerspectiveTeam\JustCheckMeOut\Block\Stateful;
use PerspectiveTeam\JustCheckMeOut\ViewModel\QuoteViewModel;
use PerspectiveTeam\SsrGraphql\ViewModel\SsrGraphqlViewModel;

/** @var Stateful $block */
/** @var Escaper $escaper */
?>

<script>
    window.justCheckMeOutApiV1.component.createCustomerEmailForm = function () {
        <?php const UNIFIED_EMAIL_GQL = <<<GRAPHQL
query unifiedEmail(\$cart_id: String!) {
  cart(cart_id: \$cart_id) {
    email
  }
  customer {
    email
  }
}
GRAPHQL; ?>

        <?php const SET_GUEST_EMAIL_ON_CART_GQL = <<<GRAPHQL
mutation setGuestEmailOnCart(\$cart_id: String!, \$email: String!) {
  setGuestEmailOnCart(input: {
    cart_id: \$cart_id,
    email: \$email
  }){
    cart {
      email
    }
  }
}
GRAPHQL; ?>

        return {
            interactive: true,
            init() {
                this.$watch('emailGqlWrapper', () => {
                    this.displayEmail = this.cartEmail() || this.customerEmail();
                });

                window.justCheckMeOutApiV1.globals.registerPlaceOrderGuard('email', 0, async (_, final) => {
                    if (final) {
                        await this.save();
                    }

                    const ok = this.displayEmail?.length > 0;
                    return {
                        state: !this.interactive ? 'pending' : (ok ? 'ok' : 'error'),
                        message: ok ? 'Email looks ok!' : 'Please fill the email field',
                    };
                });
            },
            emailGqlWrapper: <?= $block->ssrGraphqlViewModel->makeSsrGqlCall(UNIFIED_EMAIL_GQL, [
                'cart_id' => $block->quoteViewModel->getMaskedQuoteId(),
            ]) ?>,
            displayEmail: <?php
            $email = $block->quoteViewModel->getQuote()->getCustomerEmail()
                ?? $block->quoteViewModel->getQuote()->getShippingAddress()->getEmail();
            echo "'$email'";
            ?>,
            displayPassword: '',
            cartEmail() {
                return this.emailGqlWrapper?.data?.cart?.email ?? '';
            },
            customerEmail() {
                return this.emailGqlWrapper?.data?.customer?.email ?? '';
            },
            customerIsLoggedIn() {
                return !!this.customerEmail();
            },
            async save() {
                if (this.customerIsLoggedIn() || this.displayEmail === this.cartEmail()) {
                    return;
                }

                this.interactive = false;
                await window.justCheckMeOutApiV1.bus.fire('place-order.call-the-guards');

                try {
                    await window.fetchMagento2Gql(`<?= SET_GUEST_EMAIL_ON_CART_GQL ?>`, {
                        cart_id: window.justCheckMeOutApiV1.globals.cartId(),
                        email: this.displayEmail,
                    });
                } finally {
                    this.interactive = true;
                    await window.justCheckMeOutApiV1.bus.fire('place-order.call-the-guards');
                }
            }
        };
    }
</script>
