<?php
declare(strict_types=1);

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use PerspectiveTeam\JustCheckMeOut\Block\Stateful;
use PerspectiveTeam\JustCheckMeOut\ViewModel\QuoteViewModel;
use PerspectiveTeam\SsrGraphql\ViewModel\SsrGraphqlViewModel;

/** @var Stateful $block */
/** @var Escaper $escaper */
?>

<script>
    window.justCheckMeOutApiV1.component.createPlaceOrder = function () {
        <?php const PLACE_ORDER_GQL = <<<GRAPHQL
mutation placeOrder(\$card_id: String!) {
  placeOrder(input: { cart_id: \$card_id }) {
    order {
      order_number
    }
  }
}
GRAPHQL;
        ?>

        return {
            interactive: false,
            loading: false,
            buttonLabel: '<?= __('Place Order') ?>',

            guardsState: [],
            currentPaymentMethodCode: '<?= $block->quoteViewModel->getQuote()->getPayment()->getMethod() ?>',

            async loopGuards(final = false) {
                const state = [];
                for (const guard of window.justCheckMeOutApiV1.globals.getPlaceOrderGuardHandlers()) {
                    const r = await guard(this, final);
                    if (r && r.state) {
                        state.push(r);
                    }
                }
                this.guardsState = state;
                this.interactive = !final && state.filter(x => x.state !== 'ok').length === 0;
            },
            guardsHintHtml() {
                const visibleErrors = this.guardsState.filter(x => x.state !== 'ok' && !!x.message);
                if (visibleErrors.length === 0) {
                    return '';
                }

                return '<div style="display: flex; flex-direction: column; gap: 2px">'
                    + visibleErrors.map(x => `<span class="small">${x.message}</span>`).join('')
                    + '</div>';
            },

            async init() {
                await this.loopGuards();
                window.justCheckMeOutApiV1.bus.on('place-order.call-the-guards', async () => {
                    await this.loopGuards();
                })

                window.justCheckMeOutApiV1.bus.on('state.set.payment-method', payload => {
                    this.currentPaymentMethodCode = payload.code;
                })

                window.justCheckMeOutApiV1.bus.on('place-order.progress', payload => {
                    this.buttonLabel = payload;
                })
            },

            async place() {
                if (!this.interactive) {
                    return {
                        preventDefault: false,
                        orderNumber: undefined,
                        errorMessages: ['Cannot place order while not interactive.'],
                    }
                }

                let result = {
                    preventDefault: false,
                    orderNumber: undefined,
                    errorMessages: [],
                };

                try {
                    this.interactive = false;
                    this.loading = true;

                    this.buttonLabel = '<?= __('Preparing order...') ?>';
                    await this.loopGuards(true);

                    this.buttonLabel = '<?= __('Preparing payment...') ?>';
                    const hook = window.justCheckMeOutApiV1.globals.getPlaceOrderHook(this.currentPaymentMethodCode);
                    if (hook) {
                        result = await hook(this);
                    }

                    if (!result.preventDefault) {
                        this.buttonLabel = '<?= __('Placing order...') ?>';
                        const r = await window.fetchMagento2Gql(`<?= PLACE_ORDER_GQL ?>`, {
                            card_id: window.justCheckMeOutApiV1.globals.cartId(),
                        });
                        result.orderNumber = r?.data?.placeOrder?.order?.order_number;
                        result.errorMessages = r?.errors?.map(e => e.message).filter(e => e?.length > 0);
                    }

                    if (!result.orderNumber) {
                        throw new Error('No order number assigned');
                    }

                    this.buttonLabel = '<?= __('Success!') ?>';
                } catch (e) {
                    this.interactive = true;
                    this.buttonLabel = '<?= __('Place Order') ?>';
                } finally {
                    this.loading = false;
                }

                return result;
            },
            async getNextUrl() {
                return `/checkout/onepage/success`;
            },
            async placeAndGoNext() {
                const order = await this.place();
                if (order.orderNumber) {
                    window.location.href = await this.getNextUrl();
                    return
                }

                if (order.errorMessages?.length > 0) {
                    for (const e of order.errorMessages) {
                        this.$dispatch('justcheckmeout-message-main', {
                            type: 'error',
                            text: e,
                        });
                    }
                }
                this.interactive = true;
            }
        };
    }
</script>
