<?php
declare(strict_types=1);

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use PerspectiveTeam\JustCheckMeOut\ViewModel\QuoteViewModel;
use PerspectiveTeam\JustCheckMeOut\ViewModel\SsrGraphqlViewModel;

/** @var Template $block */
/** @var Escaper $escaper */

/** @var SsrGraphqlViewModel $gql */
$gql = $block->getData('ssrGqlViewModel');

/** @var QuoteViewModel $quoteViewModel */
$quoteViewModel = $block->getData('quoteViewModel');
?>

<script>
    window.psteamJustCheckMeOutApiV1.component.createPlaceOrder = function () {
        <?php const PLACE_ORDER_GQL = <<<GRAPHQL
mutation placeOrder(\$card_id: String!) {
  placeOrder(input: { cart_id: \$card_id }) {
    order {
      order_number
    }
  }
}
GRAPHQL;
        ?>

        return {
            cartId: '<?= $quoteViewModel->getMaskedQuoteId() ?>',
            currentPaymentMethodCode: '<?= $quoteViewModel->getQuote()->getPayment()->getMethod() ?>',
            init: function () {
                window.psteamJustCheckMeOutApiV1.bus.on('state.set.payment-method', payload => {
                    this.currentPaymentMethodCode = payload;
                })
            },
            place: async function () {
                const hook = window.psteamJustCheckMeOutApiV1.globals.getJsPlaceOrderHook(this.currentPaymentMethodCode);
                const result = hook !== undefined
                    ? await hook(this)
                    : {
                        preventDefault: false,
                        orderNumber: undefined,
                        errorMessage: undefined,
                    };

                if (!result.preventDefault) {
                    result.orderNumber = (await window.psteamJustCheckMeOutApiV1.fn.fetchGql(`<?= PLACE_ORDER_GQL ?>`, {
                        card_id: this.cartId,
                    })).data.placeOrder.order.order_number;
                }

                return result;
            },
            getNextUrl: async function () {
                return `/checkout/onepage/success`;
            },
            placeAndGoNext: async function () {
                await this.place();
                window.location.href = await this.getNextUrl();
            }
        };
    }
</script>
