<?php
declare(strict_types=1);

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use NeutromeLabs\JustCheckMeOut\Block\Stateful;
use NeutromeLabs\JustCheckMeOut\ViewModel\QuoteViewModel;
use NeutromeLabs\SsrGraphql\ViewModel\SsrGraphqlViewModel;

/** @var Stateful $block */
/** @var Escaper $escaper */
?>

<script>
    window.justCheckMeOutApiV1.component.createShippingMethodList = function (props = {
        refreshEvents: ['state.set.customer', 'state.set.shipping-address'],
    }) {
        <?php const SHIPPING_METHODS_LIST_GQL = <<<GRAPHQL
query shippingMethodsAvailable(\$cart_id: String!) {
  cart(cart_id: \$cart_id) {
    shipping_addresses {
      available_shipping_methods {
        carrier_code
        carrier_title
        method_code
        method_title
        price_incl_tax {
          currency
          value
        }
      }
      selected_shipping_method {
        carrier_code
        method_code
        justcheckmeout_view_html
      }
    }
  }
}
GRAPHQL; ?>

        props = {
            refreshEvents: ['state.set.customer', 'state.set.shipping-address'],
            ...props,
        }

        return {
            <?php if(!$block->configManager->getComponentConfig('shipping_method_list', 'optimistic')): ?>
            methodsGql: <?= $block->ssrGraphqlViewModel->makeSsrGqlCall(SHIPPING_METHODS_LIST_GQL, [
                'cart_id' => $block->quoteViewModel->getMaskedQuoteId(),
            ], $block->configManager->isSsr() ? null : $block->configManager->getComponentConfig('shipping_method_list', 'skeleton', true)) ?>,
            <?php endif; ?>

            interactive: true,
            methodsAvailable: [],

            uiSelectedMethod: undefined,
            selectedMethod: undefined,
            selectedMethodViewHtml: undefined,

            addressFromGqlData(data) {
                const addresses = data?.cart?.shipping_addresses;
                return !Array.isArray(addresses) || addresses.length === 0 ? null : addresses[0];
            },
            tryExtractGqlData(data, skipSelected = false) {
                const address = this.addressFromGqlData(data);
                if (!address) {
                    return;
                }

                this.methodsAvailable = address.available_shipping_methods ?? [];
                if (!skipSelected) {
                    if (
                        address.selected_shipping_method
                        && address.selected_shipping_method.carrier_code
                        && address.selected_shipping_method.method_code
                    ) {
                        const newMethodCode = `${address.selected_shipping_method.carrier_code}_${address.selected_shipping_method.method_code}`;
                        if (this.selectedMethod !== newMethodCode) {
                            this.selectedMethod = newMethodCode;
                            this.selectedMethodViewHtml = address.selected_shipping_method.justcheckmeout_view_html;
                        }
                    } else {
                        this.selectedMethod = undefined;
                        this.selectedMethodViewHtml = undefined;
                    }
                    this.uiSelectedMethod = this.selectedMethod;
                }
            },
            tryExtractGqlErrors(errors) {
                if (errors?.length > 0) {
                    for (const e of errors) {
                        this.$dispatch('justcheckmeout-message-shipping-method-list', {
                            type: 'error',
                            text: e.message,
                        });
                    }
                }
            },
            async tryRefreshEntireList(abort = undefined) {
                try {
                    this.interactive = false;

                    await this.methodsGql.refresh({}, {signal: abort?.signal});
                    this.tryExtractGqlData(this.methodsGql?.data);
                    this.tryExtractGqlErrors(this.methodsGql?.errors);
                } finally {
                    this.interactive = true;
                }
            },

            canPlaceOrder() {
                return this.selectedMethod?.length > 0;
            },

            init() {
                window.justCheckMeOutApiV1.globals.registerPlaceOrderGuard('shipping-method', 200, () => {
                    const ok = this.canPlaceOrder();
                    return {
                        state: !this.interactive ? 'pending' : (ok ? 'ok' : 'error'),
                        message: ok ? 'Shipping method selected!' : 'Please select shipping method',
                    };
                });

                this.tryExtractGqlData(this.methodsGql?.data);
                this.tryExtractGqlErrors(this.methodsGql?.errors);

                this.$watch('uiSelectedMethod', async () => {
                    if (this.uiSelectedMethod !== this.selectedMethod) {
                        await this.selectMethod(this.uiSelectedMethod);
                    }
                });

                for (const e of props.refreshEvents) {
                    window.justCheckMeOutApiV1.bus.on(e, async (_, abort) => {
                        await this.tryRefreshEntireList(abort)
                    });
                }

                if (this.methodsGql?.ssr?.response?.config) {
                    if (this.methodsGql.ssr.response.config.refresh) {
                        this.tryRefreshEntireList();
                    }
                }
            },

            async setShippingMethodOnCart(variables) {
                return await window.fetchMagento2Gql(`mutation setShippingMethod($cart_id: String!, $carrier: String!, $method: String!){
  setShippingMethodsOnCart(input: {
    cart_id: $cart_id,
    shipping_methods: [{
      carrier_code: $carrier,
      method_code: $method
    }]
  }){
    cart {
      shipping_addresses {
        available_shipping_methods {
          carrier_code
          carrier_title
          method_code
          method_title
          price_incl_tax {
            currency
            value
          }
        }
        selected_shipping_method {
          carrier_code
          method_code
          justcheckmeout_view_html
        }
      }
    }
  }
}`, variables);
            },
            async selectMethod(code) {
                if (!this.interactive) {
                    return;
                }

                try {
                    this.interactive = false;
                    await window.justCheckMeOutApiV1.bus.fire('place-order.call-the-guards');

                    const [carrier, method] = code.split('_');
                    const r = await this.setShippingMethodOnCart({
                        cart_id: window.justCheckMeOutApiV1.globals.cartId(),
                        carrier,
                        method,
                    });

                    if (r?.errors?.length > 0) {
                        this.tryExtractGqlErrors(r.errors);
                        await this.methodsGql.refresh();
                    } else {
                        this.tryExtractGqlData(r?.data?.setShippingMethodsOnCart);
                    }
                } finally {
                    this.interactive = true;
                }

                await window.justCheckMeOutApiV1.bus.fire('state.set.shipping-method', this.selectedMethod);
                await window.justCheckMeOutApiV1.bus.fire('place-order.call-the-guards');
            }
        };
    }

    <?php if($block->configManager->getComponentConfig('shipping_method_list', 'optimistic')): ?>
    window.justCheckMeOutApiV1.component.createOptimisticShippingMethodList = function (props = {
        refreshEvents: ['state.set.customer', 'state.set.shipping-address'],
        deferred: <?= $block->configManager->getComponentConfig('shipping_method_list', 'deferred') ? 'true' : 'false' ?>,
    }) {
         <?php $OPTIMISTIC_SHIPPING_METHODS_LIST_GQL = <<<GRAPHQL
query shippingMethodsAvailable(\$cart_id: String!) {
  cart(cart_id: \$cart_id) {
    shipping_addresses {
      available_shipping_methods {
        carrier_code
        carrier_title
        method_code
        method_title
        price_incl_tax {
          currency
          value
        }
        justcheckmeout_view_html
      }
      selected_shipping_method {
        carrier_code
        method_code
      }
    }
  }
}
GRAPHQL; ?>
        const realistic = window.justCheckMeOutApiV1.component.createShippingMethodList(props);
        return {
            ...realistic,

            methodsGql: <?= $block->ssrGraphqlViewModel->makeSsrGqlCall($OPTIMISTIC_SHIPPING_METHODS_LIST_GQL, [
                'cart_id' => $block->quoteViewModel->getMaskedQuoteId(),
            ], $block->configManager->isSsr() ? null : $block->configManager->getComponentConfig('shipping_method_list', 'skeleton', true)) ?>,

            updateViewHtml: function() {
                this.selectedMethodViewHtml = this.methodsAvailable
                    ?.find(m => m.carrier_code + '_' + m.method_code === this.selectedMethod)
                    ?.justcheckmeout_view_html;
            },
            tryExtractGqlData(data) {
                const currentViews = {};
                for (const v of this.methodsAvailable) {
                    currentViews[v.carrier_code + '_' + v.method_code] = v.justcheckmeout_view_html;
                }

                realistic.tryExtractGqlData.bind(this)(data, props?.deferred ?? <?= $block->configManager->getComponentConfig('shipping_method_list', 'deferred') ? 'true' : 'false' ?>);

                for (const v of this.methodsAvailable) {
                    if (
                        data?.setShippingMethodsOnCart?.cart?.shipping_addresses[0]?.selected_shipping_method?.carrier_code === v.carrier_code
                        && data?.setShippingMethodsOnCart?.cart?.shipping_addresses[0]?.selected_shipping_method?.method_code === v.method_code
                    ) {
                        this.selectedMethodViewHtml = v.justcheckmeout_view_html;
                    } else if (!v.justcheckmeout_view_html) {
                        v.justcheckmeout_view_html = currentViews[v.carrier_code + '_' + v.method_code];
                    }
                }

                this.updateViewHtml();
            },

            init() {
                realistic.init.bind(this)();
                if (props?.deferred ?? <?= $block->configManager->getComponentConfig('shipping_method_list', 'deferred') ? 'true' : 'false' ?>) {
                    window.justCheckMeOutApiV1.globals.registerPlaceOrderGuard('deferred-shipping-method', 210, async (_, final) => {
                        if (final) {
                            await realistic.selectMethod.bind(this)(this.selectedMethod);
                        }
                        return {
                            state: !this.interactive ? 'pending' : (this.canPlaceOrder() ? 'ok' : 'error')
                        };
                    });
                }
            },

            async selectMethod(code) {
                this.selectedMethod = code;
                this.updateViewHtml();

                if (props?.deferred ?? <?= $block->configManager->getComponentConfig('shipping_method_list', 'deferred') ? 'true' : 'false' ?>) {
                    await window.justCheckMeOutApiV1.bus.fire('state.set.shipping-method', this.selectedMethod);
                    await window.justCheckMeOutApiV1.bus.fire('place-order.call-the-guards');
                } else {
                    await realistic.selectMethod.bind(this)(code);
                }
            }
        }
    }
    <?php endif; ?>
</script>
