<?php
declare(strict_types=1);

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use PerspectiveTeam\JustCheckMeOut\Block\Stateful;
use PerspectiveTeam\JustCheckMeOut\ViewModel\QuoteViewModel;
use PerspectiveTeam\SsrGraphql\ViewModel\SsrGraphqlViewModel;

/** @var Stateful $block */
/** @var Escaper $escaper */
?>

<script>
    window.justCheckMeOutApiV1.component.createQuoteShippingAddressForm = function (props = {
        bookRefreshEvents: ['state.set.customer'],
        formRefreshEvents: [],
    }) {
        <?php const CUSTOMER_SHIPPING_ADDRESS_BOOK_GQL = <<<GRAPHQL
query customerAddresses {
  customer {
    default_shipping
    addresses {
      id
      telephone
      firstname
      lastname
      country_code
      region {
        region_id
        region
      }
      city
      postcode
      street
    }
  }
}
GRAPHQL; ?>

        <?php const QUOTE_SHIPPING_ADDRESSES_GQL = <<<GRAPHQL
query shippingAddresses(\$cart_id: String!) {
  cart(cart_id: \$cart_id) {
    shipping_addresses {
      firstname
      lastname
      telephone
      country {
        code
      }
      region {
        region_id
        label
      }
      city
      postcode
      street
    }
  }
}
GRAPHQL; ?>

        <?php const SET_SHIPPING_ADDRESS_ON_CART_GQL = <<<GRAPHQL
mutation setShippingAddress(\$cart_id: String!, \$customer_address_id: Int, \$address: CartAddressInput) {
  setShippingAddressesOnCart(
    input: {
      cart_id: \$cart_id,
      shipping_addresses: [{
        customer_address_id: \$customer_address_id,
        address: \$address
      }]
    }
  ) {
    cart {
      id
    }
  }

  setBillingAddressOnCart(
    input: {
      cart_id: \$cart_id,
      billing_address: {
        same_as_shipping: true
      }
    }
  ) {
    cart {
      shipping_addresses {
        firstname
        lastname
        telephone
        country {
          code
        }
        region {
          region_id
          label
        }
        city
        postcode
        street
      }
    }
  }
}
GRAPHQL; ?>

        props = {
            bookRefreshEvents: ['state.set.customer'],
            formRefreshEvents: [],
            ...props,
        }

        return {
            addressBookGql: <?= $block->ssrGraphqlViewModel->makeSsrGqlCall(CUSTOMER_SHIPPING_ADDRESS_BOOK_GQL) ?>,
            addressGql: <?= $block->ssrGraphqlViewModel->makeSsrGqlCall(QUOTE_SHIPPING_ADDRESSES_GQL, [
                'cart_id' => $block->quoteViewModel->getMaskedQuoteId(),
            ]) ?>,

            interactive: true,
            selectedAddressId: undefined,
            formData: {
                street: [],
            },
            formMetaData: {},
            focusedFieldKey: undefined,

            persistFormData() {
                localStorage.setItem('justcheckmeout::shippingAddressFormData', JSON.stringify({
                    cartId: window.justCheckMeOutApiV1.globals.cartId(),
                    formData: this.formData,
                    formMetaData: this.formMetaData,
                }))
            },
            resetPersistedFormData() {
                localStorage.removeItem('justcheckmeout::shippingAddressFormData');
            },
            tryLoadPersistedFormData() {
                const dataJson = localStorage.getItem('justcheckmeout::shippingAddressFormData');
                if (!dataJson || dataJson.length < 1) {
                    return undefined;
                }

                const data = JSON.parse(dataJson);
                if (data.cartId !== window.justCheckMeOutApiV1.globals.cartId()) {
                    this.resetPersistedFormData();
                    return undefined;
                }

                return data;
            },

            extractFormDataFromAddressModel(address) {
                return {
                    firstname: address?.firstname ?? '',
                    lastname: address?.lastname ?? '',
                    telephone: address?.telephone ?? '',
                    country_code: address?.country_code ?? address?.country?.code ?? '<?= '' // todo: get default country from config ?>',
                    region_id: address?.region?.region_id ?? null,
                    region: address?.region?.region ?? address?.region?.label ?? '',
                    city: address?.city ?? '',
                    postcode: address?.postcode ?? '',
                    street: address?.street ?? [],
                };
            },
            addressesFromAddressBook() {
                return this.addressBookGql?.data?.customer?.addresses ?? [];
            },

            tryUpdateFormDataFromGqlData(data) {
                const addresses = data?.cart?.shipping_addresses;
                const address = data?.cart?.shipping_addresses?.length > 0
                    ? addresses[0]
                    : null;

                const newFormData = this.extractFormDataFromAddressModel(address);
                if (this.focusedFieldKey) {
                    newFormData[this.focusedFieldKey] = this.formData[this.focusedFieldKey];
                }
                this.formData = newFormData;
            },
            tryUpdateFormMetaDataFromGqlData(errors) {
                const newFormMetaData = {};
                for (const k of Object.keys(this.formData)) {
                    newFormMetaData[k] = {
                        ...this.formMetaData[k] ?? {},
                        valid: true,
                        subtitle: '',
                    };
                }

                if (errors?.length > 0) {
                    for (const e of errors) {
                        for (const f of Object.keys(this.formMetaData)) {
                            if ((e.message ?? '').startsWith(`\"${f}\"`)) {
                                newFormMetaData[f].valid = false;
                                newFormMetaData[f].subtitle = e.message;
                            }
                        }
                    }
                }

                this.formMetaData = newFormMetaData;
            },
            setFieldMetaData(field, key, value) {
                this.formMetaData[field] = this.formMetaData[field] ?? {};
                this.formMetaData[field][key] = value;
            },

            canPlaceOrder() {
                return Object.keys(this.formData).length > 0 && Object.values(this.formMetaData).every(v => v.valid !== false);
            },

            init() {
                window.justCheckMeOutApiV1.globals.registerPlaceOrderGuard('unified-address', 100, () => {
                    const ok = this.canPlaceOrder();
                    return {
                        state: !this.interactive ? 'pending' : (ok ? 'ok' : 'error'),
                        message: ok ? 'Shipping address looks ok!' : 'Please complete the shipping address form',
                    };
                })

                const persistedFormData = this.tryLoadPersistedFormData();
                if (persistedFormData) {
                    this.formData = persistedFormData.formData;
                    this.formMetaData = persistedFormData.formMetaData;
                } else {
                    const defaultSelectedAddressId = parseInt(this.addressBookGql?.data?.customer?.default_shipping);
                    if (defaultSelectedAddressId > 0) { // first load with default address available
                        const address = this.addressesFromAddressBook().find(a => a.id === defaultSelectedAddressId);
                        this.selectAddressFromBook(address);
                        this.save();
                    } else {
                        this.tryUpdateFormDataFromGqlData(this.addressGql?.data);
                        this.tryUpdateFormMetaDataFromGqlData(this.addressGql?.errors);
                    }
                }

                for (const e of props.bookRefreshEvents) {
                    window.justCheckMeOutApiV1.bus.on(e, async () => {
                        try {
                            this.interactive = false;
                            await this.addressBookGql.refresh({'cart_id': window.justCheckMeOutApiV1.globals.cartId()});
                        } finally {
                            this.interactive = true;
                        }
                    });
                }

                for (const e of props.formRefreshEvents) {
                    window.justCheckMeOutApiV1.bus.on(e, async () => {
                        try {
                            this.interactive = false;

                            await this.addressGql.refresh({'cart_id': window.justCheckMeOutApiV1.globals.cartId()});
                            this.tryUpdateFormDataFromGqlData(this.addressGql?.data);
                            this.tryUpdateFormMetaDataFromGqlData(this.addressGql?.errors);
                        } finally {
                            this.interactive = true;
                        }
                    });
                }

                this.$watch('formData', () => this.persistFormData());
            },


            selectAddressFromBook(address) {
                if (address === undefined) {
                    return;
                }

                if (address?.id === this.selectedAddressId) {
                    return;
                }

                this.selectedAddressId = address?.id;
                this.formData = this.extractFormDataFromAddressModel(address);
            },
            async save() {
                try {
                    this.interactive = false;
                    await window.justCheckMeOutApiV1.bus.fire('place-order.call-the-guards');

                    let r = undefined;
                    if (!this.selectedAddressId) {
                        r = await window.fetchMagento2Gql(`<?= SET_SHIPPING_ADDRESS_ON_CART_GQL ?>`, {
                            cart_id: window.justCheckMeOutApiV1.globals.cartId(),
                            address: this.formData,
                        });
                    } else {
                        // todo: save current customer address data
                        r = await window.fetchMagento2Gql(`<?= SET_SHIPPING_ADDRESS_ON_CART_GQL ?>`, {
                            cart_id: window.justCheckMeOutApiV1.globals.cartId(),
                            customer_address_id: this.selectedAddressId,
                        });
                    }

                    if (!r.errors || r.errors.length === 0) {
                        this.tryUpdateFormDataFromGqlData(r?.data?.setBillingAddressOnCart);
                    }
                    this.tryUpdateFormMetaDataFromGqlData(r.errors);
                } finally {
                    this.interactive = true;
                    await window.justCheckMeOutApiV1.bus.fire('place-order.call-the-guards');
                }

                await window.justCheckMeOutApiV1.bus.fire('state.set.shipping-address', this);
            }
        };
    }
</script>
