<?php
declare(strict_types=1);

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use PerspectiveTeam\JustCheckMeOut\ViewModel\QuoteViewModel;
use PerspectiveTeam\SsrGraphql\ViewModel\SsrGraphqlViewModel;

/** @var Template $block */
/** @var Escaper $escaper */

/** @var SsrGraphqlViewModel $gql */
$gql = $block->getData('ssrGqlViewModel');
/** @var QuoteViewModel $quoteViewModel */
$quoteViewModel = $block->getData('quoteViewModel');
?>

<script>
    window.justCheckMeOutApiV1.component.createQuoteShippingAddressForm = function (props = {
        bookRefreshEvents: ['state.set.customer'],
        formRefreshEvents: [],
    }) {
        <?php const CUSTOMER_SHIPPING_ADDRESS_BOOK_GQL = <<<GRAPHQL
query customerAddresses {
  customer {
    default_shipping
    addresses {
      id
      telephone
      firstname
      lastname
      country_code
      region {
        region_id
        region
      }
      city
      postcode
      street
    }
  }
}
GRAPHQL; ?>

        <?php const QUOTE_SHIPPING_ADDRESSES_GQL = <<<GRAPHQL
query shippingAddresses(\$cart_id: String!) {
  cart(cart_id: \$cart_id) {
    shipping_addresses {
      firstname
      lastname
      telephone
      country {
        code
      }
      region {
        region_id
        label
      }
      city
      postcode
      street
    }
  }
}
GRAPHQL; ?>

        <?php const SET_SHIPPING_ADDRESS_ON_CART_GQL = <<<GRAPHQL
mutation setShippingAddress(\$cart_id: String!, \$customer_address_id: Int, \$address: CartAddressInput) {
  setShippingAddressesOnCart(
    input: {
      cart_id: \$cart_id,
      shipping_addresses: [{
        customer_address_id: \$customer_address_id,
        address: \$address
      }]
    }
  ) {
    cart {
      id
    }
  }

  setBillingAddressOnCart(
    input: {
      cart_id: \$cart_id,
      billing_address: {
        same_as_shipping: true
      }
    }
  ) {
    cart {
      shipping_addresses {
        firstname
        lastname
        telephone
        country {
          code
        }
        region {
          region_id
          label
        }
        city
        postcode
        street
      }
    }
  }
}
GRAPHQL; ?>

        return {
            addressBookGql: <?= $gql->makeSsrGqlCall(CUSTOMER_SHIPPING_ADDRESS_BOOK_GQL) ?>,
            addressGql: <?= $gql->makeSsrGqlCall(QUOTE_SHIPPING_ADDRESSES_GQL, [
                'cart_id' => $quoteViewModel->getMaskedQuoteId(),
            ]) ?>,

            interactive: true,
            selectedAddressId: undefined,
            formData: {},
            formErrors: {},

            extractFormDataFromAddressModel: function (address) {
                return {
                    firstname: address?.firstname ?? '',
                    lastname: address?.lastname ?? '',
                    telephone: address?.telephone ?? '',
                    country_code: address?.country_code ?? address?.country?.code ?? '<?= '' // todo: get default country from config ?>',
                    region_id: address?.region?.region_id ?? null,
                    region: address?.region?.region ?? address?.region?.label ?? '',
                    city: address?.city ?? '',
                    postcode: address?.postcode ?? '',
                    street: address?.street ?? [],
                };
            },
            addressesFromAddressBook: function () {
                return this.addressBookGqlWrapper?.data?.customer?.addresses ?? [];
            },
            selectAddressFromBook: async function (address) {
                if (address === undefined) {
                    return;
                }

                if (address?.id === this.selectedAddressId) {
                    return;
                }

                this.selectedAddressId = address?.id;
                this.formData = this.extractFormDataFromAddressModel(address);
            },

            tryExtractFormDataFromGqlData: function (data) {
                const addresses = data?.cart?.shipping_addresses;
                const address = data?.cart?.shipping_addresses?.length > 0
                    ? addresses[0]
                    : null;
                return this.extractFormDataFromAddressModel(address);
            },
            tryExtractFormErrorsFromGqlData: function (errors) {
                if (errors?.length > 0) {
                    for (const e of errors) {
                        this.$dispatch('justcheckmeout-message-shipping-address', {
                            type: 'error',
                            text: e.message,
                        });
                    }
                }
                return {};
            },

            init: function () {
                const defaultSelectedAddressId = parseInt(this.addressBookGql?.data?.customer?.default_shipping);
                if (defaultSelectedAddressId > 0 && Object.entries(this.formData).length === 0) {
                    const address = this.addressesFromAddressBook().find(a => a.id === defaultSelectedAddressId);
                    this.selectAddressFromBook(address);
                } else {
                    this.formData = this.tryExtractFormDataFromGqlData(this.addressGql?.data);
                    this.formErrors = this.tryExtractFormErrorsFromGqlData(this.addressGql?.errors);
                }

                for (const e of props.bookRefreshEvents) {
                    window.justCheckMeOutApiV1.bus.on(e, async () => {
                        try {
                            this.interactive = false;
                            await this.addressBookGql.refresh();
                        } finally {
                            this.interactive = true;
                        }
                    });
                }

                for (const e of props.formRefreshEvents) {
                    window.justCheckMeOutApiV1.bus.on(e, async () => {
                        try {
                            this.interactive = false;

                            await this.addressGql.refresh();
                            this.formData = this.tryExtractFormDataFromGqlData(this.addressGql?.data);
                            this.formErrors = this.tryExtractFormErrorsFromGqlData(this.addressGql?.errors);
                        } finally {
                            this.interactive = true;
                        }
                    });
                }
            },

            save: async function () {
                try {
                    this.interactive = false;

                    let r = undefined;
                    if (!this.selectedAddressId) {
                        r = await window.fetchMagento2Gql(`<?= SET_SHIPPING_ADDRESS_ON_CART_GQL ?>`, {
                            cart_id: window.justCheckMeOutApiV1.globals.getCartId(),
                            address: this.formData,
                        });
                    } else {
                        // todo: save current customer address data
                        r = await window.fetchMagento2Gql(`<?= SET_SHIPPING_ADDRESS_ON_CART_GQL ?>`, {
                            cart_id: window.justCheckMeOutApiV1.globals.getCartId(),
                            customer_address_id: this.selectedAddressId,
                        });
                    }

                    this.tryExtractFormDataFromGqlData(r.data?.setBillingAddressOnCart);
                    this.tryExtractFormErrorsFromGqlData(r.errors);
                } finally {
                    this.interactive = true;
                }

                window.justCheckMeOutApiV1.bus.fire('state.set.shipping-address', this);
            }
        };
    }
</script>
