<?php
declare(strict_types=1);

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use PerspectiveTeam\JustCheckMeOut\ViewModel\QuoteViewModel;
use PerspectiveTeam\SsrGraphql\ViewModel\SsrGraphqlViewModel;

/** @var Template $block */
/** @var Escaper $escaper */

/** @var SsrGraphqlViewModel $gql */
$gql = $block->getData('ssrGqlViewModel');
/** @var QuoteViewModel $quoteViewModel */
$quoteViewModel = $block->getData('quoteViewModel');
?>

<script>
    window.justCheckMeOutApiV1.component.createShippingMethodList = function (props = {
        refreshEvents: ['state.set.customer', 'state.set.shipping-address'],
    }) {
        <?php const SHIPPING_METHODS_LIST_GQL = <<<GRAPHQL
query shippingMethodsAvailable(\$cart_id: String!) {
  cart(cart_id: \$cart_id) {
    shipping_addresses {
      available_shipping_methods {
        carrier_code
        carrier_title
        method_code
        method_title
        price_incl_tax {
          currency
          value
        }
      }
      selected_shipping_method {
        carrier_code
        method_code
        details_html
      }
    }
  }
}
GRAPHQL;

        const SET_SHIPPING_METHOD_GQL = <<<GRAPHQL
mutation setShippingMethod(\$card_id: String!, \$carrier: String!, \$method: String!){
  setShippingMethodsOnCart(input: {
    cart_id: \$card_id,
    shipping_methods: [{
      carrier_code: \$carrier,
      method_code: \$method
    }]
  }){
    cart {
      shipping_addresses {
        available_shipping_methods {
          carrier_code
          carrier_title
          method_code
          method_title
          price_incl_tax {
            currency
            value
          }
        }
        selected_shipping_method {
          carrier_code
          method_code
            details_html
          }
        }
      }
    }
}
GRAPHQL;
        ?>

        return {
            methodsGql: <?= $gql->makeSsrGqlCall(SHIPPING_METHODS_LIST_GQL, [
                'cart_id' => $quoteViewModel->getMaskedQuoteId(),
            ]) ?>,

            interactive: true,
            methodsAvailable: [],
            selectedMethod: undefined,
            selectedMethodDetailsHtml: undefined,

            addressFromGqlData: function (data) {
                const addresses = data?.cart?.shipping_addresses;
                return !Array.isArray(addresses) || addresses.length === 0 ? null : addresses[0];
            },
            tryExtractGqlData: function (data) {
                const address = this.addressFromGqlData(data);
                if (!address) {
                    return;
                }

                this.methodsAvailable = address.available_shipping_methods ?? [];
                if (address.selected_shipping_method) {
                    const newMethodCode = `${address.selected_shipping_method.carrier_code}_${address.selected_shipping_method.method_code}`;
                    if (this.selectedMethod !== newMethodCode) {
                        this.selectedMethod = newMethodCode;
                        this.selectedMethodDetailsHtml = address.selected_shipping_method.details_html;
                    }
                }
            },
            tryExtractGqlErrors: function (errors) {
                if (errors?.length > 0) {
                    for (const e of errors) {
                        this.$dispatch('justcheckmeout-message-shipping-method-list', {
                            type: 'error',
                            text: e.message,
                        });
                    }
                }
            },

            init: function () {
                this.tryExtractGqlData(this.methodsGql?.data);
                this.tryExtractGqlErrors(this.methodsGql?.errors);

                for (const e of props.refreshEvents) {
                    window.justCheckMeOutApiV1.bus.on(e, async () => {
                        try {
                            this.interactive = false;

                            await this.methodsGql.refresh();
                            this.tryExtractGqlData(this.methodsGql?.data);
                            this.tryExtractGqlErrors(this.methodsGql?.errors);
                        } finally {
                            this.interactive = true;
                        }
                    });
                }
            },

            selectMethod: async function (method) {
                try {
                    this.interactive = false;

                    const r = await window.justCheckMeOutApiV1.fn.fetchGql(`<?= SET_SHIPPING_METHOD_GQL ?>`, {
                        card_id: window.justCheckMeOutApiV1.globals.getCartId(),
                        carrier: method.carrier_code,
                        method: method.method_code,
                    });
                    this.tryExtractGqlData(r.data?.setShippingMethodsOnCart);
                    this.tryExtractGqlErrors(r.errors);
                } finally {
                    this.interactive = true;
                }

                window.justCheckMeOutApiV1.bus.fire('state.set.shipping-method', this.selectedMethod);
            }
        };
    }
</script>
