<?php
declare(strict_types=1);

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use NeutromeLabs\JustCheckMeOut\Block\Stateful;
use NeutromeLabs\JustCheckMeOut\ViewModel\QuoteViewModel;
use NeutromeLabs\SsrGraphql\ViewModel\SsrGraphqlViewModel;

/** @var Stateful $block */
/** @var Escaper $escaper */
?>

<script lang="ts">
    window.justCheckMeOutApiV1.component.createTotals = function (props = {
        refreshEvents: ['state.set.shipping-method', 'state.set.payment-method'],
    }) {
<?php const CART_TOTALS_GQL = <<<GRAPHQL
query totals(\$cart_id: String!) {
  cart(cart_id: \$cart_id) {
    prices {
      subtotal_excluding_tax {
        currency
        value
      }
      applied_taxes {
        amount {
          currency
          value
        }
        label
      }
      grand_total {
        currency
        value
      }
    }
  }
}
GRAPHQL; ?>

        return {
            loading: false,

            totalsGql: <?= $block->ssrGraphqlViewModel->makeSsrGqlCall(CART_TOTALS_GQL, [
                'cart_id' => $block->quoteViewModel->getMaskedQuoteId(),
            ], $block->configManager->isSsr() ? null : $block->configManager->getComponentConfig('totals', 'skeleton', true)) ?>,

            subtotal: undefined,
            taxes: [],
            grandTotal: undefined,

            tryExtractGqlData(data) {
                if (data?.cart?.prices) {
                    this.subtotal = data.cart.prices.subtotal_excluding_tax;
                    this.taxes = data.cart.prices.applied_taxes;
                    this.grandTotal = data.cart.prices.grand_total;
                }
            },

            async refresh(signal = null) {
                this.loading = true;
                try {
                    await this.totalsGql.refresh({
                        'cart_id': window.justCheckMeOutApiV1.globals.cartId(),
                    }, {signal: signal})
                    this.tryExtractGqlData(this.totalsGql.data);
                } finally {
                    this.loading = false;
                }
            },

            init() {
                this.tryExtractGqlData(this.totalsGql?.data);
                <?php if (!$block->configManager->isSsr()): ?>
                this.refresh();
                <?php endif; ?>

                this.$watch('grandTotal', async (t1, t0) => {
                    if (t1?.value !== t0?.value) {
                        await window.justCheckMeOutApiV1.bus.fire('totals.grand-total-changed', t1.value);
                    }
                });

                for (const e of props.refreshEvents) {
                    window.justCheckMeOutApiV1.bus.on(e, async (payload, abort) => {
                        if (e === 'state.set.payment-method' && payload?.deferred) {
                            return;
                        }

                        await this.refresh(abort?.signal)
                    });
                }
            },
        };
    }
</script>
