<?php
declare(strict_types=1);

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use PerspectiveTeam\JustCheckMeOut\ViewModel\QuoteViewModel;
use PerspectiveTeam\JustCheckMeOut\ViewModel\SsrGraphqlViewModel;

/** @var Template $block */
/** @var Escaper $escaper */

/** @var SsrGraphqlViewModel $gql */
$gql = $block->getData('ssrGqlViewModel');

/** @var QuoteViewModel $quoteViewModel */
$quoteViewModel = $block->getData('quoteViewModel');
?>

<script>
    window.psteamJustCheckMeOutApiV1.component.createUnifiedAddressForm = function (customerEmailFormEl) {
        const shippingAddressComponent = window.psteamJustCheckMeOutApiV1.component.createQuoteShippingAddressForm();
        shippingAddressComponent._save = shippingAddressComponent.save;

        return {
            ...shippingAddressComponent,
            customerEmailFormEl,
            save: async function () {
                await this.customerEmailFormEl._x_dataStack[0].save(); // todo: +- ok
                await this._save();
            }
        };
    }
</script>
