<?php
declare(strict_types=1);

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use PerspectiveTeam\JustCheckMeOut\ViewModel\QuoteViewModel;
use PerspectiveTeam\SsrGraphql\ViewModel\SsrGraphqlViewModel;

/** @var Template $block */
/** @var Escaper $escaper */

/** @var SsrGraphqlViewModel $gql */
$gql = $block->getData('ssrGqlViewModel');
/** @var QuoteViewModel $quoteViewModel */
$quoteViewModel = $block->getData('quoteViewModel');
?>

<script>
    window.justCheckMeOutApiV1.component.createUnifiedAddressForm = function (customerEmailFormEl) {
        const shippingAddressComponent = window.justCheckMeOutApiV1.component.createQuoteShippingAddressForm();
        shippingAddressComponent.saveShippingAddress = shippingAddressComponent.save;

        return {
            ...shippingAddressComponent,
            customerEmailFormEl,
            unifiedInteractive: true,
            save: async function () {
                try {
                    this.unifiedInteractive = false;
                    await this.customerEmailFormEl._x_dataStack[0].save(); // todo: +- ok
                    await this.saveShippingAddress();
                } finally {
                    this.unifiedInteractive = true;
                }
            }
        };
    }
</script>
