<?php
declare(strict_types=1);

use Magento\Framework\Escaper;
use PerspectiveTeam\HeadlessComponents\Block\Headless;

/** @var Headless $block */
/** @var Escaper $escaper */
?>

<button
    class="pointer-events-auto rounded-md bg-blue-500 px-5 py-3 font-semibold text-white hover:bg-blue-600 hover:text-white"
    <?php foreach ($block->getData('attributes') ?? [] as $k => $v) {
        echo " $k=\"$v\"";
    } ?>
><?= $block->getData('text') ?></button>
