<?php
declare(strict_types=1);

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Template $block */
/** @var Escaper $escaper */
?>

<style>
    .psteam_justcheckmeout {
        font-family: Arial, sans-serif;
        display: flex;
        gap: 10px;
    }

    .psteam_justcheckmeout__customer {
        flex: 1;
        display: flex;
        flex-direction: column;
        padding: 5px;
    }

    .psteam_justcheckmeout__methods {
        flex: 1;
        display: flex;
        flex-direction: column;
        padding: 5px;
    }

    .psteam_justcheckmeout__methods__shipping {
        flex: 1;
    }

    .psteam_justcheckmeout__methods__payment {
        flex: 1;
    }

    .psteam_justcheckmeout__place {
        flex: 1;
        display: flex;
        flex-direction: column;
        padding: 5px;
    }
</style>
<div class="psteam_justcheckmeout">
    <div class="psteam_justcheckmeout__customer">
        <h2>Customer</h2>
        <?= $block->getChildHtml('unified-address-form') ?>
    </div>

    <div class="psteam_justcheckmeout__methods">
        <div class="psteam_justcheckmeout__methods__shipping">
            <h2>Shipping Method</h2>
            <?= $block->getChildHtml('shipping-method-list') ?>
        </div>
        <div class="psteam_justcheckmeout__methods__payment">
            <h2>Payment Method</h2>
            <?= $block->getChildHtml('payment-method-list') ?>
        </div>
    </div>

    <div class="psteam_justcheckmeout__place">
        <h2>Order</h2>
        <?= $block->getChildHtml('items') ?>
        <?= $block->getChildHtml('totals') ?>
        <?= $block->getChildHtml('place-button') ?>
    </div>
</div>
