<?php
declare(strict_types=1);

use Magento\Framework\Escaper;
use PerspectiveTeam\JustCheckMeOut\Block\Stateful;

/** @var Stateful $block */
/** @var Escaper $escaper */

$mediaUrl = $block->getStore()->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA);
?>

<?php foreach ($block->quoteViewModel->getQuote()->getAllVisibleItems() as $item): ?>
<div style="display: flex; gap: 10px;">
    <img src="<?= $escaper->escapeUrl($mediaUrl . 'catalog/product' . $item->getProduct()->getThumbnail()) ?>"
         style="width: 64px;"
         alt="<?= $item->getName() ?>"
         loading="lazy">
    <div style="display: flex; flex-direction: column; justify-content: space-between">
        <div style="display: flex; flex-direction: column;">
            <strong><?=  $item->getName() ?></strong>
            <span class="small"><?= $item->getSku() ?></span>
        </div>
        <div style="display: flex; flex-direction: column">
            <span class="small"><?= $item->getQty() ?> X <?= number_format(floatval($item->getPrice()), 2) ?> <?= $block->quoteViewModel->getQuote()->getQuoteCurrencyCode() ?></span>
            <span><?= number_format(floatval($item->getRowTotal()), 2) ?> <?= $block->quoteViewModel->getQuote()->getQuoteCurrencyCode() ?></span>
        </div>
    </div>
</div>
<?php endforeach; ?>
