<?php
declare(strict_types=1);

use Magento\Framework\Escaper;
use PerspectiveTeam\JustCheckMeOut\Block\Stateful;

/** @var Stateful $block */
/** @var Escaper $escaper */

$component = $block->configManager->getComponentConfig('payment-method-list', 'optimistic')
    ? "createOptimisticPaymentMethodList"
    : 'createPaymentMethodList';

$component = <<<JS
({
    ...window.justCheckMeOutApiV1.component.{$component}(),
    radioItems: function () {
        return this.methodsAvailable?.map(m => {
            return {
                id: m.code,
                label: m.title,
            };
        });
    }
})
JS;
?>

<form action="#" x-data="<?= $escaper->escapeHtmlAttr($component) ?>">
    <?= $block->headlessComponentRenderer->render('block/messages', [
        'scope' => 'payment-method-list',
    ], 'payment-method-list.messages') ?>

    <?= $block->headlessComponentRenderer->render('block/radio-list-with-collapsible-view', [
        'key' => uniqid('payment_method_'),
        'empty' => __('No payment method'),
        'props' => <<<JS
({
    items: radioItems(),
    selected: selectedMethod
})
JS,
        'wrapper' => [
            'x-effect' => 'items = radioItems(); disabled = !interactive',
            'x-model' => 'uiSelectedMethod',
        ],
        'item' => [
            'x-effect' => 'sharedViewHtml = selectedMethodViewHtml',
        ],
    ], 'payment-method-list.items') ?>
</form>
