<?php
declare(strict_types=1);

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use PerspectiveTeam\JustCheckMeOut\ViewModel\HeadlessComponentRenderer;
use PerspectiveTeam\JustCheckMeOut\ViewModel\QuoteViewModel;

/** @var Template $block */
/** @var Escaper $escaper */

/** @var QuoteViewModel $quoteViewModel */
$quoteViewModel = $block->getData('quoteViewModel');
/** @var HeadlessComponentRenderer $components */
$components = $block->getData('headlessComponentRenderer');

$radioListKey = uniqid('payment_method_');
?>

<form action="#" x-data="window.psteamJustCheckMeOut.component.createPaymentMethodList()">
    <?= $components->render('atom/button', [
        'text' => '[dev] refresh',
        'attributes' => ['type' => 'button', '@click' => 'await methodsGqlWrapper.refresh()']
    ]) ?>
    <?= $components->render('block/radio-list-with-details', [
        'key' => $radioListKey,
        'alpine' => [
            'expr' => [
                'items' => 'methodsAvailable()',
                'value' => 'item.code',
                'current' => 'currentMethod()',
                'label' => 'item.title',
            ],
            'fn' => [
                'select' => 'await selectMethod',
            ]
        ]
    ], 'justcheckmeout.onepage.payment-method-list.list') ?>
</form>
