<?php
declare(strict_types=1);

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use PerspectiveTeam\JustCheckMeOut\Block\Stateful;
use PerspectiveTeam\JustCheckMeOut\ViewModel\HeadlessComponentRenderer;
use PerspectiveTeam\JustCheckMeOut\ViewModel\QuoteViewModel;

/** @var Stateful $block */
/** @var Escaper $escaper */
?>

<div x-data="window.justCheckMeOutApiV1.component.createPlaceOrder()" style="display: flex; flex-direction: column; gap: 10px">
    <div style="display: flex; flex-direction: column;"
         @mouseover="await loopGuards()"
         x-tooltip.html.placement.bottom="guardsHintHtml()">
        <?= $block->headlessComponentRenderer->render('atom/button', [
            'label' => __('Place Order'),
            ':label' => 'buttonLabel',
            'attributes' => [
                'type' => 'button',
                'disabled' => 'true',
                ':disabled' => '!interactive',
                '@click' => 'await placeAndGoNext()',
            ]
        ]) ?>
    </div>
</div>
