<?php
declare(strict_types=1);

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use NeutromeLabs\JustCheckMeOut\Block\Stateful;
use NeutromeLabs\JustCheckMeOut\ViewModel\HeadlessComponentRenderer;
use NeutromeLabs\JustCheckMeOut\ViewModel\QuoteViewModel;

/** @var Stateful $block */
/** @var Escaper $escaper */
?>

<div x-data="window.justCheckMeOutApiV1.component.createPlaceOrder()" class="justcheckmeout__place-order">
    <div class="actions-toolbar"
         @mouseover="await loopGuards()"
         x-tooltip.html.placement.bottom="guardsHintHtml()">
        <div class="primary">
            <?= $block->headlessComponentRenderer->render('atom/button', [
                'label' => __('Place Order'),
                ':label' => 'buttonLabel',
                'attributes' => [
                    'type' => 'button',
                    'disabled' => 'true',
                    ':disabled' => '!interactive',
                    '@click' => 'await placeAndGoNext()',
                ]
            ]) ?>
        </div>
    </div>
</div>
