<?php
declare(strict_types=1);

use Magento\Framework\Escaper;
use PerspectiveTeam\JustCheckMeOut\Block\Stateful;

/** @var Stateful $block */
/** @var Escaper $escaper */

$component = $block->configManager->getComponentConfig('shipping-method-list', 'optimistic')
    ? "createOptimisticShippingMethodList"
    : 'createShippingMethodList';

$component = <<<JS
({
    ...window.justCheckMeOutApiV1.component.{$component}(),
    radioItems: function () {
        return this.methodsAvailable?.map(m => {
            return {
                id: m.carrier_code + '_' + m.method_code,
                label: m.carrier_title + ' ' + m.method_title + ' • ' + m.price_incl_tax.value + ' ' + m.price_incl_tax.currency,
            };
        });
    }
})
JS;
?>

<form action="#" x-data="<?= $escaper->escapeHtmlAttr($component) ?>">
    <div class="step-title" style="display: flex; align-items: center; gap: 10px; font-size: 2rem; padding-bottom: 10px">
        <span><?= __('Shipping Method') ?></span>
        <template x-if="!interactive">
            <?= $block->headlessComponentRenderer->render('atom/loader') ?>
        </template>
    </div>
    <?= $block->headlessComponentRenderer->render('block/messages', [
        'scope' => 'shipping-method-list',
    ], 'shipping-method-list.messages') ?>

    <template x-if="!methodsAvailable || methodsAvailable.length === 0">
        <div style="display: flex; align-items: center; justify-content: center">
            <span><?= __('No shipping information available') ?></span>
        </div>
    </template>
    <template x-if="methodsAvailable?.length > 0">
        <?= $block->headlessComponentRenderer->render('block/radio-list-with-collapsible-view', [
            'key' => uniqid('shipping_method_'),
            'props' => '{items: radioItems(), selected: selectedMethod, sharedViewHtml: selectedMethodViewHtml}',
            'wrapper' => [
                'x-effect' => 'items = radioItems(); disabled = !interactive',
                'x-model' => 'uiSelectedMethod',
            ],
            'item' => [
                'x-effect' => 'sharedViewHtml = selectedMethodViewHtml',
            ],
        ], 'shipping-method-list.items') ?>
    </template>
</form>
