<?php
declare(strict_types=1);

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use NeutromeLabs\JustCheckMeOut\Block\Stateful;
use NeutromeLabs\JustCheckMeOut\ViewModel\HeadlessComponentRenderer;
use NeutromeLabs\JustCheckMeOut\ViewModel\QuoteViewModel;

/** @var Stateful $block */
/** @var Escaper $escaper */
?>

<div class="justcheckmeout__totals"
     x-data="window.justCheckMeOutApiV1.component.createTotals()"
     :class="{'loading': loading}">
    <table class="table-totals">
        <tbody>
            <template x-if="subtotal">
                <tr class="totals sub">
                    <th class="mark" scope="row"><?= __('Subtotal') ?></th>
                    <td class="amount">
                        <span class="price" x-text="subtotal.value.toLocaleString(undefined, {minimumFractionDigits: 2}) + ' ' + subtotal.currency"></span>
                    </td>
                </tr>
            </template>
            <template x-if="shipping">
                <tr class="totals shipping">
                    <th class="mark" scope="row"><?= __('Shipping') ?></th>
                    <td class="amount">
                        <span class="price" x-text="shipping.value.toLocaleString(undefined, {minimumFractionDigits: 2}) + ' ' + shipping.currency"></span>
                    </td>
                </tr>
            </template>
            <template x-for="tax in taxes" :key="tax.label">
                <tr class="totals tax">
                    <th class="mark" scope="row" x-text="tax.label"></th>
                    <td class="amount">
                        <span class="price" x-text="tax.amount.value.toLocaleString(undefined, {minimumFractionDigits: 2}) + ' ' + tax.amount.currency"></span>
                    </td>
                </tr>
            </template>
        </tbody>
        <tfoot>
            <template x-if="grandTotal">
                <tr class="totals grand">
                    <th class="mark" scope="row"><?= __('Grand Total') ?></th>
                    <td class="amount">
                        <strong class="price" x-text="grandTotal.value.toLocaleString(undefined, {minimumFractionDigits: 2}) + ' ' + grandTotal.currency"></strong>
                    </td>
                </tr>
            </template>
        </tfoot>
    </table>
    <template x-if="!subtotal?.value && taxes?.length < 1 && !grandTotal?.value && loading">
        <div class="totals-loader">
            <?= $block->headlessComponentRenderer->render('atom/loader') ?>
        </div>
    </template>
</div>
