<?php
declare(strict_types=1);

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use PerspectiveTeam\JustCheckMeOut\Block\Stateful;
use PerspectiveTeam\JustCheckMeOut\ViewModel\HeadlessComponentRenderer;
use PerspectiveTeam\JustCheckMeOut\ViewModel\QuoteViewModel;

/** @var Stateful $block */
/** @var Escaper $escaper */
?>

<div x-data="window.justCheckMeOutApiV1.component.createTotals()"
     :style="loading ? 'animation: blink 1s linear infinite' : ''"
     x-show="true" x-collapse>
    <template x-if="subtotal">
        <div style="display: flex; justify-content: space-between">
            <span>Subtotal</span>
            <strong x-text="subtotal.value.toLocaleString(undefined, {minimumFractionDigits: 2}) + ' ' + subtotal.currency"></strong>
        </div>
    </template>
    <template x-for="tax in taxes">
        <div style="display: flex; justify-content: space-between">
            <span x-text="tax.label"></span>
            <strong x-text="tax.amount.value.toLocaleString(undefined, {minimumFractionDigits: 2}) + ' ' + tax.amount.currency"></strong>
        </div>
    </template>
    <template x-if="grandTotal">
        <div style="display: flex; justify-content: space-between">
            <span>Grand Total</span>
            <strong x-text="grandTotal.value.toLocaleString(undefined, {minimumFractionDigits: 2}) + ' ' + grandTotal.currency"></strong>
        </div>
    </template>
    <template x-if="!subtotal?.value && taxes?.length < 1 && !grandTotal?.value && loading">
        <?= $block->headlessComponentRenderer->render('atom/loader') ?>
    </template>
</div>
