<?php
declare(strict_types=1);

use Magento\Framework\Escaper;
use PerspectiveTeam\JustCheckMeOut\Block\Stateful;

/** @var Stateful $block */
/** @var Escaper $escaper */


$address = $block->quoteViewModel->getQuote()->getShippingAddress();
$allowedCountries = $block->configManager->getAllowedCountries();
$allowedCountriesJson = json_encode($allowedCountries);

$constructorId = uniqid();
$formId = uniqid('unified-address-form_');
$addressesRadioListKey = uniqid('customer-shipping-address-');
?>

<script>
    function createUnifiedAddressForm<?=$constructorId?>(customerEmailFormEl) {
        const formComponent = window.justCheckMeOutApiV1.component.createQuoteShippingAddressForm();
        return {
            ...formComponent,
            unifiedInteractive: true,
            init() {
                formComponent.init.bind(this)();
            },
            async unifiedSave() {
                try {
                    this.unifiedInteractive = false;
                    await Alpine.$data(customerEmailFormEl).save();
                    await this.save();
                } finally {
                    this.unifiedInteractive = true;
                }
            }
        }
    }
</script>
<form id="<?= $formId ?>"
      x-data="createUnifiedAddressForm<?= $constructorId ?>($el.querySelector(`[x-ref=email]`))"
      @submit.prevent="await unifiedSave()">
    <div style="flex: 1">
        <fieldset class="field" x-data="window.justCheckMeOutApiV1.component.createCustomerEmailForm()" x-ref="email">
            <div class="justcheckmeout__unified_address_form__fieldset_row">
                <?= $block->headlessComponentRenderer->render('atom/input-text', [
                    'type' => 'email',
                    'name' => 'email',
                    'label' => __('Email'),
                    'attributes' => [
                        'required' => 1,
                        'value' => $address->getEmail(),
                        'x-model' => 'displayEmail',
                        '@change' => 'await save()'
                    ]
                ], 'unified-address-form.input-email') ?>
            </div>
        </fieldset>

        <fieldset class="field">
            <div class="justcheckmeout__unified_address_form__fieldset_row">
                <?= $block->headlessComponentRenderer->render('atom/input-text', [
                    'type' => 'text',
                    'name' => 'telephone',
                    'label' => __('Telephone'),
                    'attributes' => [
                        'required' => 1,
                        'value' => $address->getTelephone(),
                        'x-model' => 'formData.telephone',
                        'x-effect' => 'state = focusedFieldKey != "telephone" && formMetaData?.telephone?.touched ? (formMetaData?.telephone?.valid ? "" : "error") : ""; subtitle = formMetaData?.telephone?.subtitle',
                        '@focusin' => 'focusedFieldKey = "telephone"',
                        '@focusout' => 'focusedFieldKey = undefined; setFieldMetaData("telephone", "touched", true); setFieldMetaData("telephone", "valid", true)',
                        '@change' => 'await unifiedSave()'
                    ]
                ], 'unified-address-form.input-telephone') ?>
            </div>

            <div class="justcheckmeout__unified_address_form__fieldset_row">
                <?= $block->headlessComponentRenderer->render('atom/input-text', [
                    'type' => 'text',
                    'name' => 'firstname',
                    'label' => __('Firstname'),
                    'attributes' => [
                        'required' => 1,
                        'value' => $address->getFirstname(),
                        'x-model' => 'formData.firstname',
                        'x-effect' => 'state = focusedFieldKey != "firstname" && formMetaData?.firstname?.touched ? (formMetaData?.firstname?.valid ? "" : "error") : ""; subtitle = formMetaData?.firstname?.subtitle',
                        '@focusin' => 'focusedFieldKey = "firstname"',
                        '@focusout' => 'focusedFieldKey = undefined; setFieldMetaData("firstname", "touched", true); setFieldMetaData("firstname", "valid", true)',
                        '@change' => 'await unifiedSave()',
                    ]
                ], 'unified-address-form.input-firstname') ?>
                <?= $block->headlessComponentRenderer->render('atom/input-text', [
                    'type' => 'text',
                    'name' => 'lastname',
                    'label' => __('Lastname'),
                    'attributes' => [
                        'required' => 1,
                        'value' => $address->getLastname(),
                        'x-model' => 'formData.lastname',
                        'x-effect' => 'state = focusedFieldKey != "lastname" && formMetaData?.lastname?.touched ? (formMetaData?.lastname?.valid ? "" : "error") : ""; subtitle = formMetaData?.lastname?.subtitle',
                        '@focusin' => 'focusedFieldKey = "lastname"',
                        '@focusout' => 'focusedFieldKey = undefined; setFieldMetaData("lastname", "touched", true); setFieldMetaData("lastname", "valid", true)',
                        '@change' => 'await unifiedSave()'
                    ]
                ], 'unified-address-form.input-lastname') ?>
            </div>

            <?php const COUNTRIES_GQL = <<<GRAPHQL
query {
  countries {
    id
    full_name_locale
  }
}
GRAPHQL;

            $countryRegionWrapperXData = <<<JS
({
    allowedCountries: {$allowedCountriesJson},
    countriesGql: {$block->ssrGraphqlViewModel->makeSsrGqlCall(COUNTRIES_GQL)},
    managedRegions: null,
    regionsLoading: false,
    init() {
        // Preselect country if only one is allowed and none is set
        if (!formData.country_code && this.allowedCountries.length === 1) {
            formData.country_code = this.allowedCountries[0];
        }

        this.\$watch('formData.country_code', async (value) => {
            const country = Alpine.\$data(\$el.querySelector(`[x-ref=country_code]`)).options.find(x => x.id === value);
            this.managedRegions = country?.regions && country.regions.length > 0 ? country.regions : null;
        });
    }
})
JS; ?>
            <div class="justcheckmeout__unified_address_form__fieldset_row"
                 x-data="<?= $escaper->escapeHtmlAttr($countryRegionWrapperXData) ?>"
            >
                <?= $block->headlessComponentRenderer->render('atom/input-select', [
                    'props' => <<<JS
({
    options: countriesGql?.data?.countries
        ?.filter(x => allowedCountries.length === 0 || allowedCountries.includes(x.id))
        ?.map(x => ({
            id: x.id,
            label: x.full_name_locale,
        })) ?? [],
    selected: formData.country_code,
})
JS,
                    'name' => 'country_code',
                    'label' => __('Country'),
                    'wrapper' => [
                        'x-ref' => 'country_code',
                        'x-effect' => <<<JS
await (async () => {
    regionsLoading = true;
    try {
        const r = await window.fetchMagento2Gql(
            `query getRegions(\$country_id: String!) {
  country(id: \$country_id) {
    available_regions {
      id
      code
      name
    }
  }
}`, {'country_id': formData.country_code});
        managedRegions = r?.data?.country?.available_regions?.map(r => {
            return {
                id: r.id,
                label: r.name,
                code: r.code
            };
        }) ?? null;
    } finally {
        regionsLoading = false;
    }
})()
JS,
                    ],
                    'select' => [
                        'required' => 1,
                        'x-model' => 'formData.country_code',
                        '@change' => 'formData.region = formData.city = formData.postcode = ""; formData.region_id = undefined; formData.street = []',
                    ],
                    'item' => [
                        ':selected' => 'option.id == formData.country_code',
                    ],
                ], 'unified-address-form.input-country') ?>
                <template x-if="managedRegions !== null">
                    <?= $block->headlessComponentRenderer->render('atom/input-select', [
                        'props' => '({selected: formData.region_id})',
                        'name' => 'region_id',
                        'label' => __('Region'),
                        'wrapper' => [
                            'x-effect' => 'options = managedRegions'
                        ],
                        'select' => [
                            'required' => 1,
                            'x-model' => 'formData.region_id',
                            '@change' => 'formData.region = undefined; await unifiedSave()',
                        ],
                        'item' => [
                            ':selected' => 'option.id == formData.region_id',
                        ],
                    ], 'unified-address-form.input-region_id') ?>
                </template>
                <?= $block->headlessComponentRenderer->render('atom/input-text', [
                    'type' => 'text',
                    'name' => 'region',
                    'label' => __('Region'),
                    'wrapper' => [
                        'x-show' => 'managedRegions === null'
                    ],
                    'attributes' => [
                        'required' => 1,
                        'value' => $address->getRegion(),
                        'x-model' => 'formData.region',
                        ':disabled' => 'regionsLoading',
                        'x-effect' => 'state = focusedFieldKey != "region" && formMetaData?.region?.touched ? (formMetaData?.region?.valid ? "" : "error") : ""; subtitle = formMetaData?.region?.subtitle',
                        '@focusin' => 'focusedFieldKey = "region"',
                        '@focusout' => 'focusedFieldKey = undefined; setFieldMetaData("region", "touched", true); setFieldMetaData("region", "valid", true)',
                        '@change' => 'formData.region_id = undefined; await unifiedSave()',
                    ]
                ], 'unified-address-form.input-region') ?>
            </div>

            <div class="justcheckmeout__unified_address_form__fieldset_row">
                <?= $block->headlessComponentRenderer->render('atom/input-text', [
                    'type' => 'text',
                    'name' => 'city',
                    'label' => __('City'),
                    'attributes' => [
                        'required' => 1,
                        'value' => $address->getCity(),
                        'x-model' => 'formData.city',
                        'x-effect' => 'state = focusedFieldKey != "city" && formMetaData?.city?.touched ? (formMetaData?.city?.valid ? "" : "error") : ""; subtitle = formMetaData?.city?.subtitle',
                        '@focusin' => 'focusedFieldKey = "city"',
                        '@focusout' => 'focusedFieldKey = undefined; setFieldMetaData("city", "touched", true); setFieldMetaData("city", "valid", true)',
                        '@change' => 'await unifiedSave()'
                    ]
                ], 'unified-address-form.input-city') ?>
                <?= $block->headlessComponentRenderer->render('atom/input-text', [
                    'type' => 'text',
                    'name' => 'postcode',
                    'label' => __('Postcode'),
                    'attributes' => [
                        'required' => 1,
                        'value' => $address->getPostcode(),
                        'x-model' => 'formData.postcode',
                        'x-effect' => 'state = focusedFieldKey != "postcode" && formMetaData?.postcode?.touched ? (formMetaData?.postcode?.valid ? "" : "error") : ""; subtitle = formMetaData?.postcode?.subtitle',
                        '@focusin' => 'focusedFieldKey = "postcode"',
                        '@focusout' => 'focusedFieldKey = undefined; setFieldMetaData("postcode", "touched", true); setFieldMetaData("postcode", "valid", true)',
                        '@change' => 'await unifiedSave()'
                    ]
                ], 'unified-address-form.input-postcode') ?>
            </div>

            <div class="justcheckmeout__unified_address_form__fieldset_row">
                <?= $block->headlessComponentRenderer->render('atom/input-text', [
                    'type' => 'text',
                    'name' => 'street_1',
                    'label' => __('Street'),
                    'attributes' => [
                        'required' => 1,
                        'value' => $address->getStreetLine(1),
                        'x-model' => 'formData.street[0]',
                        'x-effect' => 'state = focusedFieldKey != "street" && formMetaData?.street?.touched ? (formMetaData?.street?.valid ? "" : "error") : ""; subtitle = formMetaData?.street?.subtitle',
                        '@focusin' => 'focusedFieldKey = "street"',
                        '@focusout' => 'focusedFieldKey = undefined; setFieldMetaData("street", "touched", true); setFieldMetaData("street", "valid", true)',
                        '@change' => 'await unifiedSave()'
                    ]
                ], 'unified-address-form.input-street_1') ?>
            </div>
            <div class="justcheckmeout__unified_address_form__fieldset_row">
                <?= $block->headlessComponentRenderer->render('atom/input-text', [
                    'type' => 'text',
                    'name' => 'street_2',
                    'attributes' => [
                        'value' => $address->getStreetLine(2),
                        'x-model' => 'formData.street[1]',
                        '@focusin' => 'focusedFieldKey = "street"',
                        '@focusout' => 'focusedFieldKey = undefined; setFieldMetaData("street", "touched", true); setFieldMetaData("street", "valid", true)',
                        '@change' => 'await unifiedSave()'
                    ]
                ], 'unified-address-form.input-street_2') ?>
            </div>
        </fieldset>
    </div>
</form>
