<?php
declare(strict_types=1);

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use PerspectiveTeam\JustCheckMeOut\ViewModel\HeadlessComponentRenderer;

/** @var Template $block */
/** @var Escaper $escaper */

/** @var HeadlessComponentRenderer $components */
$components = $block->getData('headlessComponentRenderer');

foreach ($block->getData('fields') as $key => $data) {
    echo $components->render('block/input-text', [
        'label' => $data['label'],
        'attributes' => array_merge(array_diff_key($data, array_flip(['label'])) ?? [], [
            'name' => $key,
        ])
    ], 'justcheckmeout.onepage.address-fieldset.input-' . $key);
}
