<?php
declare(strict_types=1);

use Magento\Framework\Escaper;
use PerspectiveTeam\JustCheckMeOut\Block\Headless;

/** @var Headless $block */
/** @var Escaper $escaper */
?>

<div class="input-text">
    <?php if ($label = $block->getData('label')): ?>
        <label for="<?= $escaper->escapeHtmlAttr($block->getData('attributes/name')) ?>">
            <?= $label ?>
        </label>
    <?php endif; ?>
    <?= $block->headlessComponentRenderer->render('atom/input-text', [
        'attributes' => $block->getData('attributes') ?? []
    ]) ?>
</div>
