<?php
declare(strict_types=1);

use Magento\Framework\Escaper;
use PerspectiveTeam\HeadlessComponents\Block\Headless;

/** @var Headless $block */
/** @var Escaper $escaper */
?>

<script>
    window.justCheckMeOutApiV1.component.createInputSelect = function (props = {
        selectedId: undefined,
        initImpl: function () {
        },
        searchImpl: async function (text) {
            return [];
        }
    }) {
        return {
            selectedId: props.selectedId,
            options: [],
            search: async function(text) {
                if (!props.searchImpl) {
                    return;
                }

                if (text.length < 3) {
                    // return;
                }

                this.options = await (props.searchImpl.bind(this))(text);
            },
            init: async function () {
                if (props.initImpl) {
                    props.initImpl.bind(this)();
                }
            }
        };
    };
</script>
