<?php

use Magento\Framework\Escaper;
use NeutromeLabs\HeadlessComponents\Block\Headless;

/** @var Headless $block */
/** @var Escaper $escaper */

$scope = $block->getData('scope');
?>

<div x-data="justcheckmeoutHeadlessCreateMessages()"
     @justcheckmeout-message-<?= $scope ?>.window="add($event.detail)">
    <template x-if="messages.length > 0">
        <div class="messages">
            <template x-for="message in messages" :key="message.id">
                <div :class="'message ' + (message.type || 'notice')">
                    <span x-text="message.text"></span>
                </div>
            </template>
        </div>
    </template>
</div>
