<?php
declare(strict_types=1);

use Magento\Framework\Escaper;
use PerspectiveTeam\HeadlessComponents\Block\Headless;

/** @var Headless $block */
/** @var Escaper $escaper */
?>

<template x-for="item in <?= $block->getData('alpine/expr/items') ?>"
          :key="<?= $block->getData('alpine/expr/value') ?>">
    <div>
        <p>
            <input type="radio"
                   name="<?= $block->getData('key') ?>"
                   :value="<?= $block->getData('alpine/expr/value') ?>"
                   :checked="<?= $block->getData('alpine/expr/current') ?> === $el.value"
                   @click="<?= $block->getData('alpine/expr/select') ?>"
                   <?= $block->getData('alpine/expr/disabled')
                       ? ':disabled="' . $block->getData('alpine/expr/disabled') . '"'
                       : ''
                   ?>/>
            <span x-text="<?= $block->getData('alpine/expr/label') ?>"></span>
        </p>
        <?php if ($block->getData('alpine/expr/details')): ?>
            <template x-if="<?= $block->getData('alpine/expr/current') ?> === <?= $block->getData('alpine/expr/value') ?>">
                <div x-html="<?= $block->getData('alpine/expr/details') ?>"></div>
            </template>
        <?php endif; ?>
    </div>
</template>
