<?php

use Magento\Framework\Escaper;
use PerspectiveTeam\HeadlessComponents\Block\Headless;

/** @var Headless $block */
/** @var Escaper $escaper */

$attributesHtml = $block->attributesHtmlGenerator->generate($block->getData('attributes'));
?>

<button class="button action continue primary" <?= $attributesHtml ?> style="display: flex; justify-content: center; align-items: center;gap: 10px;">
    <?= $block->getRenderer()->render('component/headless/atom/loader', [
        'attributes' => [
            ':style' => "loading ? 'margin-left: -24px; opacity: 1' : 'margin-left: -29px; opacity: 0'",
        ]
    ]) ?>
    <span <?php if ($text = $block->getData(':label')) echo "x-text=\"$text\"" ?>>
        <?= $block->getData('label') ?>
    </span>
</button>
