<?php
declare(strict_types=1);

use Magento\Framework\Escaper;
use PerspectiveTeam\JustCheckMeOut\Block\Headless;

/** @var Headless $block */
/** @var Escaper $escaper */
?>

<div class="flex flex-col gap-3 mb-3">
    <?php
    foreach ($block->getData('fields') as $key => $data) {
        echo $block->headlessComponentRenderer->render('block/input-text', [
            'label' => array_key_exists('label', $data) ? $data['label'] : null,
            'attributes' => array_merge(array_diff_key($data, array_flip(['label'])) ?? [], [
                'name' => $key,
            ])
        ], 'justcheckmeout.onepage.address-fieldset.input-' . $key);
    }
    ?>
</div>
