<?php
declare(strict_types=1);

use Magento\Framework\Escaper;
use PerspectiveTeam\HeadlessComponents\Block\Headless;

/** @var Headless $block */
/** @var Escaper $escaper */
?>

<div x-data="window.justCheckMeOutApiV1.component.createInputSelect(<?= $block->getData('alpine/props') ?>)"
     x-modelable="selectedId"
    <?php foreach ($block->getData('attributes/wrapper') ?? [] as $k => $v) {
        echo " $k=\"$v\"";
    } ?>
>
    <div x-data="{filled: true}"
         class="relative w-full font-medium text-gray-700">
        <div class="pl-2.5 text-xs transition-transform duration-200 absolute"
             :class="filled ? ' top-[0.4375rem] left-0 translate-y-0' : 'opacity-0 translate-y-full'">
            <?php if ($label = $block->getData('label')): ?>
                <label for="<?= $escaper->escapeHtmlAttr($block->getData('attributes/name')) ?>">
                    <span><?= $label ?> <span x-text="$el.getAttribute('required') && '*'"></span></span>
                </label>
            <?php endif; ?>
        </div>

        <div class="flex items-center gap-4">
            <select class="block w-full form-input grow renderer-text !pt-3 !pb-2 !pl-4"
                    x-model="selectedId"
                <?php foreach ($block->getData('attributes/input') ?? [] as $k => $v) {
                    echo " $k=\"$v\"";
                } ?>
            >
                <option :value="undefined" disabled></option>
                <template x-for="option in options">
                    <option :value="option.id"
                            :selected="option.id == selectedId"
                            x-text="option.label"></option>
                </template>
            </select>
        </div>
    </div>
</div>
