<?php
declare(strict_types=1);

use Magento\Framework\Escaper;
use PerspectiveTeam\JustCheckMeOut\Block\Headless;

/** @var Headless $block */
/** @var Escaper $escaper */

$attributes = $block->getData('attributes') ?? [];
$attributes['type'] = $attributes['type'] ?? 'text';
?>

<div x-data="{filled: <?= array_key_exists('value', $attributes) && !empty($attributes['value']) ? 'true' : 'false' ?>}"
     class="relative w-full font-medium text-gray-700">
    <div class="pl-2.5 text-xs transition-transform duration-200 absolute"
         :class="filled ? ' top-[0.4375rem] left-0 translate-y-0' : 'opacity-0 translate-y-full'">
        <?php if ($label = $block->getData('label')): ?>
            <label for="<?= $escaper->escapeHtmlAttr($block->getData('attributes/name')) ?>">
                <span><?= $label ?> <span x-text="$el.getAttribute('required') && '*'"></span></span>
            </label>
        <?php endif; ?>
    </div>


    <div class="flex items-center gap-4">
        <input class="block w-full form-input grow renderer-text !pt-5 !pb-2"
               :placeholder="'<?= $block->getData('label') ?>' + ($el.getAttribute('required') ? '*' : '')"
               @change="filled = $el.value.length > 0"
            <?php foreach ($attributes as $k => $v) {
                echo " $k=\"$v\"";
            } ?>>
    </div>
</div>
